import test from 'node:test';
import assert from 'node:assert/strict';
import { read, sourceFiles } from '../testSupport/sourceFiles.mjs';

function importFromConstants(source) {
  return source.match(/import \{(?<names>[^}]+)\} from ['"]\.\.\/constants\.js['"];/)?.groups.names
    .split(',')
    .map(name => name.trim())
    .filter(Boolean) ?? [];
}

test('HTML/template source does not contain duplicate class attributes on one tag', () => {
  const files = ['index.html', ...sourceFiles('src')];
  const duplicateClassTag = /<[^>]*\bclass\s*=\s*['"][^'"]*['"][^>]*\bclass\s*=\s*['"]/i;

  for (const file of files) {
    assert.doesNotMatch(read(file), duplicateClassTag, `${file} has duplicate class attributes in one tag`);
  }
});

test('category editor imports shared state filter keys when referenced', () => {
  const source = read('src/ui/rangeStateFiltersEditor.js');
  if (!/\bSTATE_FILTER_KEYS\b/.test(source)) return;
  assert.ok(importFromConstants(source).includes('STATE_FILTER_KEYS'), 'rangeStateFiltersEditor.js references STATE_FILTER_KEYS but does not import it from constants.js');
});

test('category editor delegates matching-rule composition to its focused module', () => {
  const categoryEditor = read('src/ui/categoryEditor.js');
  const matchingRulesEditor = read('src/ui/matchingRulesEditor.js');

  assert.match(categoryEditor, /import \{ renderMatchingRulesEditor \} from ['"]\.\/matchingRulesEditor\.js['"];/);
  assert.match(categoryEditor, /root\.appendChild\(renderMatchingRulesEditor\(cat, \{/);
  assert.doesNotMatch(categoryEditor, /\blistEditor\(|renderAllowedRaritiesEditor|parseTypedRowIdValue|normalizeRowIdValue|Allowed Item Name Patterns|Allowed UI Category IDs|Allowed Item IDs|Allowed Rarities/);
  assert.match(matchingRulesEditor, /export function renderMatchingRulesEditor\(category, deps = \{\}\)/);
  assert.match(matchingRulesEditor, /ruleGrid\.className = 'grid cols-2'/);

  const itemOrderingIndex = categoryEditor.indexOf('root.appendChild(itemOrdering)');
  const matchingRulesIndex = categoryEditor.indexOf('root.appendChild(renderMatchingRulesEditor');
  const rangesIndex = categoryEditor.indexOf('renderRangeStateFiltersEditor(rules');
  assert.ok(itemOrderingIndex < matchingRulesIndex && matchingRulesIndex < rangesIndex);
});

test('category editor delegates Range and State composition with narrow data flow and stable order', () => {
  const categoryEditor = read('src/ui/categoryEditor.js');
  const filterEditor = read('src/ui/rangeStateFiltersEditor.js');

  assert.ok(categoryEditor.includes("import { renderRangeStateFiltersEditor } from './rangeStateFiltersEditor.js';"));
  const delegationStart = categoryEditor.indexOf('const { ranges, states } = renderRangeStateFiltersEditor(rules, {');
  const delegationEnd = categoryEditor.indexOf('root.append(ranges, states);', delegationStart);
  const delegation = categoryEditor.slice(delegationStart, delegationEnd);
  assert.ok(delegationStart >= 0 && delegationEnd > delegationStart);
  assert.ok(delegation.includes('markDirty,'));
  assert.ok(delegation.includes('scheduleRenderList'));
  assert.ok(delegation.indexOf('updateCategoryIssueSummary();') < delegation.indexOf('maybeAutoGenerateDescription(reason);'));
  assert.doesNotMatch(categoryEditor, /rangeSliderControl|segmentedControl|RANGE_FILTER_NAMES|STATE_FILTER_NAMES|for \(const filter of RANGE_FILTERS\)|renderStateFilterCard/);

  assert.match(filterEditor, /export function renderRangeStateFiltersEditor\(rules, deps = \{\}\)/);
  assert.match(filterEditor, /const RANGE_FILTER_NAMES = Object\.fromEntries\(RANGE_FILTERS/);
  assert.match(filterEditor, /const STATE_FILTER_NAMES = Object\.fromEntries\(STATE_FILTERS/);
  assert.match(filterEditor, /rangeGrid\.className = 'grid cols-3 range-filter-grid'/);
  assert.match(filterEditor, /stateGrid\.className = 'grid cols-3'/);
  assert.doesNotMatch(filterEditor, /categoryEditor\.js|\.\.\/app\.js|getCategories|getSelectedIndex|renderAll|createScheduledRenderList/);

  const matchingRules = categoryEditor.indexOf('root.appendChild(renderMatchingRulesEditor');
  const filters = categoryEditor.indexOf('renderRangeStateFiltersEditor(rules');
  const advanced = categoryEditor.indexOf("const advanced = document.createElement('details')");
  assert.ok(matchingRules >= 0 && filters > matchingRules && advanced > filters);

  const rangeStateSchedule = categoryEditor.indexOf('const scheduleRenderList = createScheduledRenderList(renderList)');
  const colorSchedule = categoryEditor.indexOf('scheduleRenderList: createScheduledRenderList(renderList)');
  assert.ok(rangeStateSchedule >= 0 && colorSchedule > rangeStateSchedule, 'Range/State must share one scheduler distinct from Color');
});

test('category editor delegates Color composition while preserving top-grid order and independent scheduling', () => {
  const categoryEditor = read('src/ui/categoryEditor.js');
  const colorEditor = read('src/ui/colorEditor.js');

  assert.match(categoryEditor, /import \{ renderColorEditor \} from ['"]\.\/colorEditor\.js['"];/);
  assert.match(categoryEditor, /const colorCard = renderColorEditor\(cat, \{\s*markDirty,\s*markDirtyAndRenderList,\s*scheduleRenderList: createScheduledRenderList\(renderList\)\s*\}\);/);
  assert.match(categoryEditor, /topEditorGrid\.append\(basicEditor\.card, colorCard\)/);
  assert.doesNotMatch(categoryEditor, /colorToHex|colorToHexRGBA|hexToRgb01|hexToRgba01|rgbaCss|componentTo255|canonicalHexRgba|decideHexRgbaCommit|decideRgbCommit|decideAlphaCommit|renderColorSection|color-native-input|hex-color-input|alpha-slider/);
  assert.match(colorEditor, /export function renderColorEditor\(category, deps = \{\}\)/);
  assert.match(colorEditor, /export function normalizeRgbInputValue\(value, committedValue\)/);
  assert.doesNotMatch(colorEditor, /categoryEditor\.js|createScheduledRenderList|\brenderList\s*[=,}]|getCategories|getSelectedIndex|renderAll/);

  const filterSchedule = categoryEditor.indexOf('const scheduleRenderList = createScheduledRenderList(renderList)');
  const colorSchedule = categoryEditor.indexOf('scheduleRenderList: createScheduledRenderList(renderList)');
  assert.ok(filterSchedule >= 0 && colorSchedule > filterSchedule, 'Color and Range/State filters must receive distinct scheduler instances');
});

test('category editor delegates Basics and description ownership through a narrow controller', () => {
  const categoryEditor = read('src/ui/categoryEditor.js');
  const basicEditor = read('src/ui/basicEditor.js');

  assert.match(categoryEditor, /import \{ renderBasicEditor \} from ['"]\.\/basicEditor\.js['"];/);
  assert.match(categoryEditor, /export \{ getBasicSwitchWarnings \} from ['"]\.\/basicEditor\.js['"];/);
  assert.match(categoryEditor, /const basicEditor = renderBasicEditor\(cat, \{/);
  assert.match(categoryEditor, /topEditorGrid\.append\(basicEditor\.card, colorCard\)/);
  assert.doesNotMatch(categoryEditor, /Basics<\/h3>|basic-switch-validation|description-generate-row|replaceGeneratedDescription|copyGeneratedDescription|numberInput\('Order'|textInput\('Name'|generateCategoryDescription|applyGeneratedDescriptionChange/);

  assert.match(basicEditor, /export function renderBasicEditor\(category, deps = \{\}\)/);
  assert.match(basicEditor, /return \{ card: basics, maybeAutoGenerateDescription, refreshValidation \};/);
  assert.doesNotMatch(basicEditor, /categoryEditor\.js|\.\.\/app\.js|getCategories|getSelectedIndex|renderAll|createScheduledRenderList|renderColorEditor|renderRangeStateFiltersEditor|renderMatchingRulesEditor/);

  const basicsIndex = categoryEditor.indexOf('basicEditor.card');
  const colorIndex = categoryEditor.indexOf('colorCard', basicsIndex);
  assert.ok(basicsIndex >= 0 && colorIndex > basicsIndex, 'Basics must precede Color in the top grid');

  const orderingStart = categoryEditor.indexOf('const itemOrdering = renderItemOrderingEditor');
  const orderingEnd = categoryEditor.indexOf('root.appendChild(itemOrdering)', orderingStart);
  const ordering = categoryEditor.slice(orderingStart, orderingEnd);
  assert.ok(ordering.indexOf('onValidationChanged: basicEditor.refreshValidation') < ordering.indexOf("onOrderingChanged: () => basicEditor.maybeAutoGenerateDescription('item ordering changed')"));

  const matchingStart = categoryEditor.indexOf('onRulesChanged: reason => {');
  const matchingEnd = categoryEditor.indexOf('},', matchingStart);
  const matching = categoryEditor.slice(matchingStart, matchingEnd);
  const matchingOrder = ['basicEditor.refreshValidation();', 'basicEditor.maybeAutoGenerateDescription(reason);', 'renderList();']
    .map(statement => matching.indexOf(statement));
  assert.ok(matchingOrder.every(index => index >= 0));
  assert.deepEqual(matchingOrder, [...matchingOrder].sort((a, b) => a - b));

  const filterStart = categoryEditor.indexOf('onFiltersChanged: reason => {');
  const filterEnd = categoryEditor.indexOf('},', filterStart);
  const filterCallback = categoryEditor.slice(filterStart, filterEnd);
  assert.ok(filterCallback.indexOf('updateCategoryIssueSummary();') < filterCallback.indexOf('basicEditor.maybeAutoGenerateDescription(reason);'));
});

test('range filter key references are imported or locally declared', () => {
  for (const file of sourceFiles('src')) {
    const source = read(file);
    if (!/\bRANGE_FILTER_KEYS\b/.test(source)) continue;
    const importsRangeKeys = /import \{[^}]*\bRANGE_FILTER_KEYS\b[^}]*\} from ['"][^'"]*constants\.js['"];/.test(source);
    const declaresRangeKeys = /\b(?:const|let|var)\s+RANGE_FILTER_KEYS\b/.test(source);
    assert.ok(importsRangeKeys || declaresRangeKeys, `${file} references RANGE_FILTER_KEYS without importing or declaring it`);
  }
});

test('app imports import validation summary helpers it references', () => {
  const source = read('src/app.js');
  const importNames = source.match(/import \{(?<names>[\s\S]*?)\} from ['"]\.\/importValidationSummary\.js['"];/)?.groups.names
    .split(',')
    .map(name => name.trim())
    .filter(Boolean) ?? [];

  for (const helper of ['reviewableImportFindings']) {
    if (!new RegExp(`\\b${helper}\\b`).test(source)) continue;
    assert.ok(importNames.includes(helper), `src/app.js references ${helper} but does not import it from importValidationSummary.js`);
  }
});

test('importText does not keep an unused importSummary binding', () => {
  const source = read('src/app.js');
  assert.doesNotMatch(source, /const\s+importSummary\s*=/);
  assert.match(source, /applyValidatedConfig\(validation\);/);
  assert.match(source, /function loadPreset\(preset\)[\s\S]*?return importText\(preset\.data, preset\.sourceLabel \|\| 'Preset'\);/);
  assert.match(source, /bindChange\('fileInput',[\s\S]*?await importText\(await readImportFileText\(file\), file\.name\);/);
  assert.match(source, /if \(!\(await importText\(text, ''\)\)\)/);
});

test('empty state startup actions use preset callbacks without owning import parsing', () => {
  const editor = read('src/ui/categoryEditor.js');
  assert.doesNotMatch(editor, /Start with <strong>Import\/Paste<\/strong> or <strong>Upload<\/strong>/);
  assert.match(editor, /Start with:/);
  assert.match(editor, /Load basic presets/);
  assert.match(editor, /Load advanced presets/);
  assert.doesNotMatch(editor, /Load presets based on SortaKinda/);
  assert.match(editor, /Import bundled basic preset categories/);
  assert.match(editor, /Import bundled advanced preset categories/);
  assert.match(editor, /Change appearance and other settings in Preferences\./);
  assert.match(editor, /Click \? for more information about this app\./);
  assert.match(editor, /loadBasicPresets/);
  assert.match(editor, /loadAdvancedPresets/);
  assert.doesNotMatch(editor, /BASIC_PRESET_BASE64|ADVANCED_PRESET_BASE64|SORTAKINDA_PRESET_BASE64|parseImportedText|validateConfig|importText/);
});

test('app owns bundled preset import through normal import path', () => {
  const app = read('src/app.js');
  assert.match(app, /import \{ PRESETS \} from '\.\/presets\.js';/);
  assert.match(app, /function loadPreset\(preset\) \{/);
  assert.match(app, /if \(!preset\?\.data\) \{/);
  assert.match(app, /Preset is not available\./);
  assert.match(app, /return importText\(preset\.data, preset\.sourceLabel \|\| 'Preset'\);/);
  assert.match(app, /function loadBasicPresets\(\)/);
  assert.match(app, /function loadAdvancedPresets\(\)/);
  assert.match(app, /preset => preset\.id === 'basic'/);
  assert.match(app, /preset => preset\.id === 'advanced'/);
  assert.match(app, /loadBasicPresets, loadAdvancedPresets,/);

  const presets = read('src/presets.js');
  assert.match(presets, /sourceLabel: 'Basic presets'/);
  assert.match(presets, /sourceLabel: 'Advanced presets'/);
});

test('package scripts include test and exhaustive combined check commands', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.equal(pkg.scripts?.test, 'node --test');
  assert.ok(pkg.scripts?.check);
  assert.match(pkg.scripts.check, /node scripts\/check-javascript-syntax\.mjs/);
  assert.match(pkg.scripts.check, /node scripts\/check-imports\.mjs/);
  assert.match(pkg.scripts.check, /node --test/);
});

test('legacy import summary and appearance modal alias stay retired', () => {
  const app = read('src/app.js');
  const config = read('src/config.js');
  const preferences = read('src/ui/preferencesModal.js');
  assert.doesNotMatch(config, /buildImportSummary/);
  assert.doesNotMatch(config, /summary:\s*buildImportSummary|\bsummary\b/);
  assert.match(config, /Mutates obj in place:/);
  assert.match(app, /function applyValidatedConfig\(validation\) \{[\s\S]*?applyConfigReplacement\(data, validation\.config,[\s\S]*?data = candidate;[\s\S]*?advanceDataRevision\(\);/);
  assert.doesNotMatch(preferences, /showAppearanceModal/);
});
