import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DEFAULT_EDITOR_PREFERENCES,
  EDITOR_PREFERENCES_KEY,
  LOOKUP_CACHE_KEY,
  loadEditorPreferences,
  loadLookupCache,
  normalizeLookupCache,
  normalizeEditorPreferences,
  persistEditorPreferences
} from '../src/state.js';

function memoryStorage(initial = new Map()) {
  return {
    getItem(key) { return initial.has(key) ? initial.get(key) : null; },
    setItem(key, value) { initial.set(key, String(value)); },
    removeItem(key) { initial.delete(key); }
  };
}

test('normalizeEditorPreferences preserves valid preference values', () => {
  assert.deepEqual(normalizeEditorPreferences({ theme: 'aetherial', density: 'compact', autoGenerateDescriptions: true, autoLookupImportedIds: false }), {
    theme: 'aetherial',
    density: 'compact',
    autoGenerateDescriptions: true,
    autoLookupImportedIds: false
  });
});

test('normalizeEditorPreferences falls back for invalid values', () => {
  assert.deepEqual(normalizeEditorPreferences({ theme: 'laser', density: 'tiny' }), DEFAULT_EDITOR_PREFERENCES);
});

test('loadEditorPreferences falls back when JSON is invalid', () => {
  const storage = memoryStorage(new Map([[EDITOR_PREFERENCES_KEY, '{not json']]));
  assert.deepEqual(loadEditorPreferences(storage), DEFAULT_EDITOR_PREFERENCES);
});

test('loadEditorPreferences falls back when storage is unavailable', () => {
  const storage = { getItem() { throw new Error('blocked'); } };
  assert.deepEqual(loadEditorPreferences(storage), DEFAULT_EDITOR_PREFERENCES);
});

test('persistEditorPreferences stores only normalized editor preferences', () => {
  const backing = new Map();
  const storage = memoryStorage(backing);
  const saved = persistEditorPreferences({ theme: 'dalamud', density: 'compact', autoGenerateDescriptions: true, autoLookupImportedIds: false, exportedData: true }, storage);
  assert.deepEqual(saved, { theme: 'dalamud', density: 'compact', autoGenerateDescriptions: true, autoLookupImportedIds: false });
  assert.equal(backing.get(EDITOR_PREFERENCES_KEY), JSON.stringify(saved));
});

test('normalizeEditorPreferences defaults auto-generate descriptions off for old or invalid preferences', () => {
  const oldPreferences = normalizeEditorPreferences({ theme: 'dark', density: 'compact' });
  assert.equal(oldPreferences.autoGenerateDescriptions, false);
  assert.equal(oldPreferences.autoLookupImportedIds, true);
  assert.equal(normalizeEditorPreferences({ autoGenerateDescriptions: 'yes', autoLookupImportedIds: 'no' }).autoGenerateDescriptions, false);
  assert.equal(normalizeEditorPreferences({ autoGenerateDescriptions: 'yes', autoLookupImportedIds: 'no' }).autoLookupImportedIds, true);
});

function assertNormalizedLookupCache(cache) {
  assert.deepEqual(Object.keys(cache).sort(), ['Item', 'ItemUICategory']);
  assert.equal(Object.getPrototypeOf(cache.Item), Object.prototype);
  assert.equal(Object.getPrototypeOf(cache.ItemUICategory), Object.prototype);
  assert.notEqual(cache.Item, cache.ItemUICategory);
}

test('normalizeLookupCache rejects malformed persisted cache shapes', () => {
  for (const value of [null, [], 'cache', 42, true, new Date(), { Item: [], ItemUICategory: null }, { Item: { 1: 'Potion' }, ItemUICategory: 'invalid' }]) {
    const cache = normalizeLookupCache(value);
    assertNormalizedLookupCache(cache);
    if (value?.Item && !Array.isArray(value.Item)) assert.deepEqual(cache.Item, { 1: 'Potion' });
    else assert.deepEqual(cache.Item, {});
    assert.deepEqual(cache.ItemUICategory, {});
  }
});

test('normalizeLookupCache keeps only string names and retains lookup sentinels', () => {
  const cache = normalizeLookupCache({
    Item: { 1: 'Potion', 2: '(name unavailable)', 3: 'not looked up', 4: null, 5: 50, 6: false },
    ItemUICategory: { 7: 'Weapons', 8: {}, 9: ['invalid'] }
  });

  assertNormalizedLookupCache(cache);
  assert.deepEqual(cache, {
    Item: { 1: 'Potion', 2: '(name unavailable)', 3: 'not looked up' },
    ItemUICategory: { 7: 'Weapons' }
  });
});

test('normalizeLookupCache creates independent buckets without mutating persisted data', () => {
  const source = { Item: { 1: 'Potion' }, ItemUICategory: { 2: 'Arms' } };
  const cache = normalizeLookupCache(source);

  assertNormalizedLookupCache(cache);
  assert.notEqual(cache.Item, source.Item);
  assert.notEqual(cache.ItemUICategory, source.ItemUICategory);
  cache.Item['1'] = 'Hi-Potion';
  assert.equal(source.Item['1'], 'Potion');
});

test('loadLookupCache parses and normalizes storage data, including failures', () => {
  const validStorage = memoryStorage(new Map([[LOOKUP_CACHE_KEY, JSON.stringify({ Item: { 1: 'Potion' }, ItemUICategory: { 2: 'Weapons' } })]]));
  assert.deepEqual(loadLookupCache(validStorage), { Item: { 1: 'Potion' }, ItemUICategory: { 2: 'Weapons' } });

  for (const raw of ['null', '[]', '"cache"', '{not json}', JSON.stringify({ Item: ['invalid'], ItemUICategory: { 2: 2 } })]) {
    const cache = loadLookupCache(memoryStorage(new Map([[LOOKUP_CACHE_KEY, raw]])));
    assertNormalizedLookupCache(cache);
    assert.deepEqual(cache, { Item: {}, ItemUICategory: {} });
  }
  assert.deepEqual(loadLookupCache({ getItem() { throw new Error('blocked'); } }), { Item: {}, ItemUICategory: {} });
});
