import { escapeHtml, requireScopedEl, setStatus } from '../dom.js';
import { closeModal, openModal } from '../modals.js';
import { applyGeneratedDescriptionChange } from '../categoryChanges.js';
import { generateCategoryDescription, isUsefulGeneratedDescription } from '../descriptionGenerator.js';
import { INT32_MAX, INT32_MIN, isSignedInt32Scalar } from '../filterScalars.js';
import { validateCategoryName, validateCategoryOrder, validateCategoryPriority } from '../validation.js';
import { numberInput, switchInput, textInput } from './formControls.js';

export function getBasicSwitchWarnings(category) {
  return validateCategoryName(category).filter(item => item.field === 'Pinned' && item.severity === 'warning');
}

function debounce(fn, delay = 160) {
  let timer = null;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

export function renderBasicEditor(category, deps = {}) {
  const {
    categories = [],
    markDirty,
    markDirtyAndRenderList = () => markDirty({ renderList: true }),
    renderList,
    onNameChanged = () => {},
    onCategoryValidationChanged = () => {},
    lookupName,
    commitActiveField = () => {},
    getEditorPreferences = () => ({ autoGenerateDescriptions: false }),
    copyTextToClipboard = async () => false
  } = deps;

  const basics = document.createElement('div');
  basics.className = 'card basics-card';
  const basicsTitle = document.createElement('div');
  basicsTitle.className = 'filter-card-title basics-title-row';
  basicsTitle.innerHTML = '<h3>Basics</h3>';

  function updateBasicSwitchWarnings() {
    const box = requireScopedEl(basics, '.basic-switch-validation', 'basic switch validation');
    const findings = getBasicSwitchWarnings(category);
    box.hidden = findings.length === 0;
    box.innerHTML = findings.map(item => `<p class="field-${item.severity}">${escapeHtml(item.message)}</p>`).join('');
  }

  function refreshValidation() {
    onCategoryValidationChanged();
    updateBasicSwitchWarnings();
  }

  const basicsActions = document.createElement('div');
  basicsActions.className = 'filter-card-actions';
  basicsActions.append(
    switchInput('Enabled', category.Enabled, value => { category.Enabled = value; refreshValidation(); markDirtyAndRenderList(); }),
    switchInput('Pinned', category.Pinned, value => { category.Pinned = value; refreshValidation(); markDirtyAndRenderList(); })
  );
  const basicSwitchArea = document.createElement('div');
  basicSwitchArea.className = 'basic-switch-area';
  basicSwitchArea.appendChild(basicsActions);
  const basicSwitchValidation = document.createElement('div');
  basicSwitchValidation.className = 'validation-list basic-switch-validation';
  basicSwitchValidation.hidden = true;
  basicSwitchArea.appendChild(basicSwitchValidation);
  basicsTitle.appendChild(basicSwitchArea);

  const debouncedRenderList = debounce(renderList);
  let descriptionInput = null;

  function generateDescription() {
    return generateCategoryDescription(category, { lookupName });
  }

  function applyGeneratedDescription(text) {
    return applyGeneratedDescriptionChange(category, text, () => {
      if (descriptionInput) descriptionInput.value = text;
      refreshValidation();
      markDirty();
      renderList();
    });
  }

  function maybeAutoGenerateDescription(reason = 'rule change') {
    void reason;
    if (!getEditorPreferences().autoGenerateDescriptions) return false;
    if (String(category.Description || '').trim()) return false;
    const generated = generateDescription();
    if (!isUsefulGeneratedDescription(generated)) return false;
    return applyGeneratedDescription(generated);
  }

  function updateSidebarText(valueSetter, options = {}) {
    valueSetter();
    if (options.updateHeaderTitle) onNameChanged();
    refreshValidation();
    markDirty();
    if (options.autoGenerate) maybeAutoGenerateDescription(options.autoGenerate);
    debouncedRenderList();
  }

  function showGenerateDescriptionConfirmation(generated) {
    const wrap = document.createElement('div');
    wrap.innerHTML = `
      <p class="hint">Review before replacing the current description.</p>
      <h3>Current description</h3><p>${escapeHtml(category.Description)}</p>
      <h3>Generated description</h3><p>${escapeHtml(generated)}</p>
      <div class="row modal-action-row modal-action-row-loose">
        <button id="replaceGeneratedDescription" class="primary">Replace description</button>
        <button id="copyGeneratedDescription">Copy generated text</button>
        <button id="cancelGeneratedDescription">Cancel</button>
      </div>`;
    openModal('Generate description', wrap);
    requireScopedEl(wrap, '#replaceGeneratedDescription', 'generated description confirmation').onclick = () => {
      if (!applyGeneratedDescription(generated)) setStatus('Description already matches the generated text.', 'ok');
      closeModal();
    };
    requireScopedEl(wrap, '#copyGeneratedDescription', 'generated description confirmation').onclick = async () => {
      const ok = await copyTextToClipboard(generated);
      setStatus(ok ? 'Generated description copied.' : 'Copy failed. Select the text manually.', ok ? 'ok' : 'warn');
    };
    requireScopedEl(wrap, '#cancelGeneratedDescription', 'generated description confirmation').onclick = closeModal;
  }

  const grid = document.createElement('div');
  grid.className = 'grid basic-fields-grid';
  const nameField = textInput('Name', category.Name, value => updateSidebarText(() => { category.Name = value; }, { updateHeaderTitle: true }), { validate: () => validateCategoryName(category).filter(item => item.field === 'Name'), validateOnInput: true, onBlur: () => maybeAutoGenerateDescription('name changed') });
  const descriptionField = textInput('Description', category.Description, value => updateSidebarText(() => { category.Description = value; }), { validate: () => validateCategoryName(category).filter(item => item.field === 'Description'), validateOnInput: true });
  descriptionField.classList.add('description-generate-field');
  descriptionInput = requireScopedEl(descriptionField, 'input', 'description field');
  const generateButton = document.createElement('button');
  generateButton.type = 'button';
  generateButton.className = 'generate-description-button';
  generateButton.textContent = 'Generate';
  generateButton.title = 'Generate description for this category';
  generateButton.setAttribute('aria-label', 'Generate description for this category');
  generateButton.onclick = () => {
    commitActiveField();
    const generated = generateDescription();
    if (category.Description === generated) setStatus('Description already matches the generated text.', 'ok');
    else if (!String(category.Description || '').trim()) applyGeneratedDescription(generated);
    else showGenerateDescriptionConfirmation(generated);
  };
  const descriptionValidation = requireScopedEl(descriptionField, '.validation-list', 'description field validation');
  const descriptionRow = document.createElement('div');
  descriptionRow.className = 'description-generate-row';
  descriptionInput.replaceWith(descriptionRow);
  descriptionRow.append(descriptionInput, generateButton);
  descriptionField.insertBefore(descriptionRow, descriptionValidation);
  grid.append(nameField, descriptionField);

  const metaGrid = document.createElement('div');
  metaGrid.className = 'grid basic-meta-grid';
  metaGrid.append(
    numberInput('Order', category.Order, value => { category.Order = value; refreshValidation(); markDirtyAndRenderList(); }, '1', INT32_MIN, INT32_MAX, { validate: () => validateCategoryOrder(category, categories), validateNumber: isSignedInt32Scalar, requireJsonNumber: true, inputErrorMessage: 'Order must be a signed 32-bit integer.', preserveStoredDisplay: true }),
    numberInput('Priority', category.Priority, value => { category.Priority = value; refreshValidation(); markDirtyAndRenderList(); }, '1', INT32_MIN, INT32_MAX, { validate: () => validateCategoryPriority(category, categories), validateNumber: isSignedInt32Scalar, requireJsonNumber: true, inputErrorMessage: 'Priority must be a signed 32-bit integer.', preserveStoredDisplay: true })
  );

  basics.append(basicsTitle, grid, metaGrid);
  refreshValidation();

  return { card: basics, maybeAutoGenerateDescription, refreshValidation };
}
