import { escapeHtml, requireScopedEl, setStatus } from '../dom.js';
import { closeModal, openModal } from '../modals.js';
import { applyGeneratedDescriptionChange } from '../categoryChanges.js';
import { generateCategoryDescription, isUsefulGeneratedDescription } from '../descriptionGenerator.js';
import { INT32_MAX, INT32_MIN, isSignedInt32Scalar } from '../filterScalars.js';
import { validateCategoryName, validateCategoryOrder, validateCategoryPriority } from '../validation.js';
import { numberInput, switchInput, textInput } from './formControls.js';

export function createBasicEditorMessages(translate) {
  return Object.freeze({
    title: translate('basics.title'),
    enabled: translate('basics.enabled.label'),
    pinned: translate('basics.pinned.label'),
    name: translate('basics.name.label'),
    description: translate('basics.description.label'),
    generate: Object.freeze({
      action: translate('basics.description.generate.action'),
      accessible: translate('basics.description.generate.accessible')
    }),
    confirmation: Object.freeze({
      title: translate('basics.description.confirmation.title'),
      guidance: translate('basics.description.confirmation.guidance'),
      current: translate('basics.description.confirmation.current'),
      generated: translate('basics.description.confirmation.generated'),
      replace: translate('basics.description.confirmation.replace'),
      copy: translate('basics.description.confirmation.copy'),
      cancel: translate('basics.description.confirmation.cancel')
    }),
    status: Object.freeze({
      current: translate('basics.description.status.current'),
      copied: translate('basics.description.status.copied'),
      copyFailed: translate('basics.description.status.copyFailed')
    }),
    order: Object.freeze({
      label: translate('basics.order.label'),
      error: translate('basics.order.error')
    }),
    priority: Object.freeze({
      label: translate('basics.priority.label'),
      error: translate('basics.priority.error')
    })
  });
}

export function getBasicSwitchWarnings(category) {
  return validateCategoryName(category).filter(item => item.field === 'Pinned' && item.severity === 'warning');
}

function debounce(fn, delay = 160) {
  let timer = null;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

export function renderBasicEditor(category, deps = {}) {
  const {
    categories = [],
    markDirty,
    markDirtyAndRenderList = () => markDirty({ renderList: true }),
    renderList,
    onNameChanged = () => {},
    onCategoryValidationChanged = () => {},
    lookupName,
    commitActiveField = () => {},
    getEditorPreferences = () => ({ autoGenerateDescriptions: false }),
    copyTextToClipboard = async () => false,
    translate
  } = deps;
  const messages = createBasicEditorMessages(translate);

  const basics = document.createElement('div');
  basics.className = 'card basics-card';
  const basicsTitle = document.createElement('div');
  basicsTitle.className = 'filter-card-title basics-title-row';
  const basicsHeading = document.createElement('h3');
  basicsHeading.textContent = messages.title;
  basicsTitle.appendChild(basicsHeading);

  function updateBasicSwitchWarnings() {
    const box = requireScopedEl(basics, '.basic-switch-validation', 'basic switch validation');
    const findings = getBasicSwitchWarnings(category);
    box.hidden = findings.length === 0;
    box.innerHTML = findings.map(item => `<p class="field-${item.severity}">${escapeHtml(item.message)}</p>`).join('');
  }

  function refreshValidation() {
    onCategoryValidationChanged();
    updateBasicSwitchWarnings();
  }

  const basicsActions = document.createElement('div');
  basicsActions.className = 'filter-card-actions';
  basicsActions.append(
    switchInput(messages.enabled, category.Enabled, value => { category.Enabled = value; refreshValidation(); markDirtyAndRenderList(); }),
    switchInput(messages.pinned, category.Pinned, value => { category.Pinned = value; refreshValidation(); markDirtyAndRenderList(); })
  );
  const basicSwitchArea = document.createElement('div');
  basicSwitchArea.className = 'basic-switch-area';
  basicSwitchArea.appendChild(basicsActions);
  const basicSwitchValidation = document.createElement('div');
  basicSwitchValidation.className = 'validation-list basic-switch-validation';
  basicSwitchValidation.hidden = true;
  basicSwitchArea.appendChild(basicSwitchValidation);
  basicsTitle.appendChild(basicSwitchArea);

  const debouncedRenderList = debounce(renderList);
  let descriptionInput = null;

  function generateDescription() {
    return generateCategoryDescription(category, { lookupName });
  }

  function applyGeneratedDescription(text) {
    return applyGeneratedDescriptionChange(category, text, () => {
      if (descriptionInput) descriptionInput.value = text;
      refreshValidation();
      markDirty();
      renderList();
    });
  }

  function maybeAutoGenerateDescription(reason = 'rule change') {
    void reason;
    if (!getEditorPreferences().autoGenerateDescriptions) return false;
    if (String(category.Description || '').trim()) return false;
    const generated = generateDescription();
    if (!isUsefulGeneratedDescription(generated)) return false;
    return applyGeneratedDescription(generated);
  }

  function updateSidebarText(valueSetter, options = {}) {
    valueSetter();
    if (options.updateHeaderTitle) onNameChanged();
    refreshValidation();
    markDirty();
    if (options.autoGenerate) maybeAutoGenerateDescription(options.autoGenerate);
    debouncedRenderList();
  }

  function showGenerateDescriptionConfirmation(generated) {
    const wrap = document.createElement('div');
    wrap.innerHTML = `
      <p class="hint">${escapeHtml(messages.confirmation.guidance)}</p>
      <h3>${escapeHtml(messages.confirmation.current)}</h3><p>${escapeHtml(category.Description)}</p>
      <h3>${escapeHtml(messages.confirmation.generated)}</h3><p>${escapeHtml(generated)}</p>
      <div class="row modal-action-row modal-action-row-loose">
        <button id="replaceGeneratedDescription" class="primary">${escapeHtml(messages.confirmation.replace)}</button>
        <button id="copyGeneratedDescription">${escapeHtml(messages.confirmation.copy)}</button>
        <button id="cancelGeneratedDescription">${escapeHtml(messages.confirmation.cancel)}</button>
      </div>`;
    openModal(messages.confirmation.title, wrap);
    requireScopedEl(wrap, '#replaceGeneratedDescription', 'generated description confirmation').onclick = () => {
      if (!applyGeneratedDescription(generated)) setStatus(messages.status.current, 'ok');
      closeModal();
    };
    requireScopedEl(wrap, '#copyGeneratedDescription', 'generated description confirmation').onclick = async () => {
      const ok = await copyTextToClipboard(generated);
      setStatus(ok ? messages.status.copied : messages.status.copyFailed, ok ? 'ok' : 'warn');
    };
    requireScopedEl(wrap, '#cancelGeneratedDescription', 'generated description confirmation').onclick = closeModal;
  }

  const grid = document.createElement('div');
  grid.className = 'grid basic-fields-grid';
  const nameField = textInput(messages.name, category.Name, value => updateSidebarText(() => { category.Name = value; }, { updateHeaderTitle: true }), { validate: () => validateCategoryName(category).filter(item => item.field === 'Name'), validateOnInput: true, onBlur: () => maybeAutoGenerateDescription('name changed') });
  const descriptionField = textInput(messages.description, category.Description, value => updateSidebarText(() => { category.Description = value; }), { validate: () => validateCategoryName(category).filter(item => item.field === 'Description'), validateOnInput: true });
  descriptionField.classList.add('description-generate-field');
  descriptionInput = requireScopedEl(descriptionField, 'input', 'description field');
  const generateButton = document.createElement('button');
  generateButton.type = 'button';
  generateButton.className = 'generate-description-button';
  generateButton.textContent = messages.generate.action;
  generateButton.title = messages.generate.accessible;
  generateButton.setAttribute('aria-label', messages.generate.accessible);
  generateButton.onclick = () => {
    commitActiveField();
    const generated = generateDescription();
    if (category.Description === generated) setStatus(messages.status.current, 'ok');
    else if (!String(category.Description || '').trim()) applyGeneratedDescription(generated);
    else showGenerateDescriptionConfirmation(generated);
  };
  const descriptionValidation = requireScopedEl(descriptionField, '.validation-list', 'description field validation');
  const descriptionRow = document.createElement('div');
  descriptionRow.className = 'description-generate-row';
  descriptionInput.replaceWith(descriptionRow);
  descriptionRow.append(descriptionInput, generateButton);
  descriptionField.insertBefore(descriptionRow, descriptionValidation);
  grid.append(nameField, descriptionField);

  const metaGrid = document.createElement('div');
  metaGrid.className = 'grid basic-meta-grid';
  metaGrid.append(
    numberInput(messages.order.label, category.Order, value => { category.Order = value; refreshValidation(); markDirtyAndRenderList(); }, '1', INT32_MIN, INT32_MAX, { validate: () => validateCategoryOrder(category, categories), validateNumber: isSignedInt32Scalar, requireJsonNumber: true, inputErrorMessage: messages.order.error, preserveStoredDisplay: true }),
    numberInput(messages.priority.label, category.Priority, value => { category.Priority = value; refreshValidation(); markDirtyAndRenderList(); }, '1', INT32_MIN, INT32_MAX, { validate: () => validateCategoryPriority(category, categories), validateNumber: isSignedInt32Scalar, requireJsonNumber: true, inputErrorMessage: messages.priority.error, preserveStoredDisplay: true })
  );

  basics.append(basicsTitle, grid, metaGrid);
  refreshValidation();

  return { card: basics, maybeAutoGenerateDescription, refreshValidation };
}
