import { el, escapeHtml, requireEl, requireScopedEl, setStatus, syncButtonTooltip } from '../dom.js';
import { setDetailsSummary } from './detailsSummary.js';
import { clone, makeId, nextCategorySortValue } from '../config.js';
import { openModal, closeModal } from '../modals.js';
import { validateCategory } from '../validation.js';
import { renderBasicEditor } from './basicEditor.js';
import { renderItemOrderingEditor } from './itemOrderingEditor.js';
import { renderMatchingRulesEditor } from './matchingRulesEditor.js';
import { renderColorEditor } from './colorEditor.js';
import { renderRangeStateFiltersEditor } from './rangeStateFiltersEditor.js';
import { applySelectedCategoryCandidate, selectedCategoryStructuralFocusPlan } from '../categoryChanges.js';
import { animateReorderMotion, cancelReorderMotion, captureReorderMotion } from '../reorderMotion.js';
import { textActionAvailable } from '../actionAvailability.js';
import { INT32_MAX, isSignedInt32Scalar } from '../filterScalars.js';
import { parseJsonText } from '../importExport.js';
import { buildEmptyState } from './emptyState.js';

export function createCategoryEditorMessages(translate) {
  return Object.freeze({
    unnamed: translate('categoryEditor.fallback.unnamed'),
    issueLabel: count => translate(count === 1 ? 'categoryEditor.validation.one' : 'categoryEditor.validation.many', { count }),
    duplicate: translate('categoryEditor.duplicate.action'),
    actions: Object.freeze({
      moveUp: name => translate('categoryEditor.moveUp.accessible', { name }),
      moveDown: name => translate('categoryEditor.moveDown.accessible', { name }),
      duplicate: name => translate('categoryEditor.duplicate.accessible', { name }),
      delete: name => translate('categoryEditor.delete.accessible', { name })
    }),
    deleteConfirmation: Object.freeze({
      title: translate('categoryEditor.delete.title'),
      questionParts: name => translate.rich('categoryEditor.delete.question', { name }),
      warning: translate('categoryEditor.delete.warning'),
      confirm: translate('categoryEditor.delete.confirm'),
      cancel: translate('categoryEditor.delete.cancel')
    }),
    advanced: Object.freeze({
      title: translate('categoryEditor.advanced.title'),
      hint: translate('categoryEditor.advanced.hint'),
      apply: translate('categoryEditor.advanced.apply')
    }),
    rawJson: Object.freeze({
      parseLabel: translate('categoryEditor.rawJson.parseLabel'),
      noChanges: translate('categoryEditor.rawJson.noChanges'),
      invalid: error => translate('categoryEditor.rawJson.invalid', { error })
    })
  });
}

function createScheduledRenderList(renderList) {
  let scheduled = false;
  return () => {
    if (scheduled) return;
    scheduled = true;
    const flush = () => {
      scheduled = false;
      renderList();
    };
    if (typeof window !== 'undefined' && typeof window.requestAnimationFrame === 'function') {
      window.requestAnimationFrame(flush);
    } else {
      setTimeout(flush, 16);
    }
  };
}

export function renderEmptyStateIfNeeded({
  categories,
  root,
  setSelectedIndex,
  translate,
  loadBasicPresets,
  loadAdvancedPresets,
  commitActiveField,
  emptyStateBuilder = buildEmptyState
}) {
  if (categories.length) return false;
  setSelectedIndex(-1);
  root.appendChild(emptyStateBuilder({ translate, loadBasicPresets, loadAdvancedPresets, commitActiveField }));
  return true;
}

export function renderEditor(deps) {
  const { getCategories, getSelectedIndex, setSelectedIndex, ensureShape, markDirty, markDirtyAndRenderList = () => markDirty({ renderList: true }), renderAll, renderList, renumberCategories, openRegexToItemIdsTool, listEditorDeps, lookupName, commitActiveField = () => {}, getEditorPreferences = () => ({ autoGenerateDescriptions: false }), copyTextToClipboard = async () => false, loadBasicPresets = null, loadAdvancedPresets = null, translate } = deps;
  const messages = createCategoryEditorMessages(translate);
  const scheduleRenderList = createScheduledRenderList(renderList);
  let selectedIndex = getSelectedIndex();
  const cats = getCategories();
  const root = requireEl('editor');
  cancelReorderMotion(root);
  root.innerHTML = '';

  if (renderEmptyStateIfNeeded({ categories: cats, root, setSelectedIndex, translate, loadBasicPresets, loadAdvancedPresets, commitActiveField })) return;
  if (selectedIndex < 0 || selectedIndex >= cats.length) { setSelectedIndex(0); selectedIndex = 0; }

  const cat = cats[selectedIndex];
  ensureShape(cat);

  const header = document.createElement('div');
  header.className = 'card';
  header.innerHTML = `
    <div class="row section-header-row">
      <div class="category-header-title">
        <div class="category-header-title-row">
          <h2 class="flush-heading">${escapeHtml(cat.Name || messages.unnamed)}</h2>
          <span class="ui-badge ui-badge-warning validation-badge category-validation-summary" hidden></span>
        </div>
      </div>
      <div class="row category-header-actions">
        <button id="moveUp" class="icon-button movement-button">↑</button>
        <button id="moveDown" class="icon-button movement-button">↓</button>
        <button id="duplicateCat" class="small">${escapeHtml(messages.duplicate)}</button>
        <button id="deleteCat" class="icon-button danger">🗑</button>
      </div>
    </div>
  `;
  root.appendChild(header);

  function updateHeaderTitle() {
    const title = requireScopedEl(header, '.flush-heading', 'category header');
    title.textContent = cat.Name || messages.unnamed;
  }

  function getCategoryIssueFindings(category = cat, allCategories = cats) {
    return validateCategory(category, allCategories).filter(item => item.severity === 'error' || item.severity === 'warning');
  }

  function updateCategoryIssueSummary() {
    const summary = requireScopedEl(header, '.category-validation-summary', 'category header');
    const findings = getCategoryIssueFindings();
    summary.hidden = findings.length === 0;
    summary.textContent = findings.length ? messages.issueLabel(findings.length) : '';
  }

  const basicEditor = renderBasicEditor(cat, {
    categories: cats,
    markDirty,
    markDirtyAndRenderList,
    renderList,
    onNameChanged: updateHeaderTitle,
    onCategoryValidationChanged: updateCategoryIssueSummary,
    lookupName,
    commitActiveField,
    getEditorPreferences,
    copyTextToClipboard,
    translate
  });

  const topEditorGrid = document.createElement('div');
  topEditorGrid.className = 'top-editor-grid';
  const colorCard = renderColorEditor(cat, {
    markDirty,
    markDirtyAndRenderList,
    scheduleRenderList: createScheduledRenderList(renderList),
    translate
  });
  topEditorGrid.append(basicEditor.card, colorCard);
  root.appendChild(topEditorGrid);

  const itemOrdering = renderItemOrderingEditor(cat, {
    markDirty,
    renderList,
    listEditorDeps,
    onValidationChanged: basicEditor.refreshValidation,
    onOrderingChanged: () => basicEditor.maybeAutoGenerateDescription('item ordering changed'),
    openRawCategoryEditor: () => {
      const advanced = root.querySelector('details.advanced-category-card');
      const raw = advanced?.querySelector('#rawCategory');
      if (!advanced || !raw) return;
      advanced.open = true;
      raw.focus();
      raw.scrollIntoView({ block: 'nearest' });
    },
    translate
  });
  root.appendChild(itemOrdering);

  const rules = cat.Rules;
  root.appendChild(renderMatchingRulesEditor(cat, {
    categories: cats,
    markDirty,
    onRulesChanged: reason => {
      basicEditor.refreshValidation();
      basicEditor.maybeAutoGenerateDescription(reason);
      renderList();
    },
    openRegexToItemIdsTool,
    listEditorDeps,
    translate
  }));

  const { ranges, states } = renderRangeStateFiltersEditor(rules, {
    markDirty,
    onFiltersChanged: reason => {
      updateCategoryIssueSummary();
      basicEditor.maybeAutoGenerateDescription(reason);
    },
    scheduleRenderList,
    translate
  });
  root.append(ranges, states);

  const advanced = document.createElement('details');
  advanced.className = 'card advanced-category-card';
  advanced.innerHTML = `
    <summary></summary>
    <div class="details-body">
      <p class="hint">${escapeHtml(messages.advanced.hint)}</p>
      <textarea class="raw" id="rawCategory">${escapeHtml(JSON.stringify(cat, null, 2))}</textarea>
      <div class="row modal-action-row">
        <button id="applyRawCategory">${escapeHtml(messages.advanced.apply)}</button>
      </div>
    </div>
  `;
  setDetailsSummary(advanced, { title: messages.advanced.title, badges: [], issueCount: 0 });
  root.appendChild(advanced);

  const actionName = cat.Name || messages.unnamed;
  const actionLabels = {
    moveUp: messages.actions.moveUp(actionName),
    moveDown: messages.actions.moveDown(actionName),
    duplicateCat: messages.actions.duplicate(actionName),
    deleteCat: messages.actions.delete(actionName)
  };
  el('moveUp').disabled = selectedIndex <= 0;
  el('moveDown').disabled = selectedIndex >= cats.length - 1;

  for (const [id, label] of Object.entries(actionLabels)) {
    const button = el(id);
    button.setAttribute('aria-label', label);
    syncButtonTooltip(button, label);
  }

  function restoreStructuralActionFocus(action) {
    for (const targetKey of selectedCategoryStructuralFocusPlan(action, selectedIndex, cats.length)) {
      const target = targetKey === 'selected-category'
        ? document.querySelector('.cat-item[aria-current="true"]')
        : el(targetKey);
      if (target && !target.disabled && !target.hidden && document.contains(target)) {
        target.focus();
        return true;
      }
    }
    return false;
  }

  el('moveUp').onclick = () => {
    commitActiveField();
    if (selectedIndex <= 0) return;
    const positions = captureReorderMotion(el('categoryList'));
    [cats[selectedIndex - 1], cats[selectedIndex]] = [cats[selectedIndex], cats[selectedIndex - 1]];
    selectedIndex--; setSelectedIndex(selectedIndex);
    if (el('autoRenumberDrag').checked) renumberCategories();
    markDirty();
    renderAll();
    animateReorderMotion(el('categoryList'), positions);
    restoreStructuralActionFocus('move-up');
  };
  el('moveDown').onclick = () => {
    commitActiveField();
    if (selectedIndex >= cats.length - 1) return;
    const positions = captureReorderMotion(el('categoryList'));
    [cats[selectedIndex + 1], cats[selectedIndex]] = [cats[selectedIndex], cats[selectedIndex + 1]];
    selectedIndex++; setSelectedIndex(selectedIndex);
    if (el('autoRenumberDrag').checked) renumberCategories();
    markDirty();
    renderAll();
    animateReorderMotion(el('categoryList'), positions);
    restoreStructuralActionFocus('move-down');
  };
  el('duplicateCat').onclick = () => {
    commitActiveField();
    const copy = clone(cat);
    copy.Id = makeId();
    copy.Name = (copy.Name || 'Category') + ' Copy';
    const nextSortValue = nextCategorySortValue(cats);
    const copyOrder = isSignedInt32Scalar(copy.Order) ? copy.Order : null;
    const copyPriority = isSignedInt32Scalar(copy.Priority) ? copy.Priority : null;
    if (copyOrder === null || copyPriority === null || copyOrder >= INT32_MAX || copyPriority >= INT32_MAX) {
      copy.Order = nextSortValue;
      copy.Priority = nextSortValue;
    } else {
      copy.Order = copyOrder + 1;
      copy.Priority = copyPriority + 1;
    }
    cats.splice(selectedIndex + 1, 0, copy);
    selectedIndex++; setSelectedIndex(selectedIndex);
    markDirty();
    renderAll();
    restoreStructuralActionFocus('duplicate');
  };
  el('deleteCat').onclick = () => {
    commitActiveField();
    const wrap = document.createElement('div');
    const question = document.createElement('p');
    for (const part of messages.deleteConfirmation.questionParts(cat.Name || messages.unnamed)) {
      if (part.type === 'text') {
        question.append(part.value);
      } else {
        const strong = document.createElement('strong');
        strong.textContent = part.value;
        question.appendChild(strong);
      }
    }
    wrap.innerHTML = `
      <p class="hint">${escapeHtml(messages.deleteConfirmation.warning)}</p>
      <div class="row modal-action-row modal-action-row-loose">
        <button id="confirmDeleteCat" class="danger">${escapeHtml(messages.deleteConfirmation.confirm)}</button>
        <button id="cancelDeleteCat">${escapeHtml(messages.deleteConfirmation.cancel)}</button>
      </div>
    `;
    wrap.prepend(question);
    openModal(messages.deleteConfirmation.title, wrap);
    requireScopedEl(wrap, '#confirmDeleteCat', 'delete category confirmation').onclick = () => {
      commitActiveField();
      cats.splice(selectedIndex, 1);
      selectedIndex = Math.min(selectedIndex, cats.length - 1); setSelectedIndex(selectedIndex);
      closeModal();
      markDirty();
      renderAll();
      restoreStructuralActionFocus('delete');
    };
    requireScopedEl(wrap, '#cancelDeleteCat', 'delete category confirmation').onclick = closeModal;
  };
  const rawCategory = el('rawCategory');
  const applyRawCategory = el('applyRawCategory');
  const syncRawCategoryAvailability = () => { applyRawCategory.disabled = !textActionAvailable(rawCategory.value); };
  syncRawCategoryAvailability();
  rawCategory.addEventListener('input', syncRawCategoryAvailability);
  applyRawCategory.onclick = () => {
    try {
      const candidate = parseJsonText(rawCategory.value, { label: messages.rawJson.parseLabel });
      const changed = applySelectedCategoryCandidate({ categories: cats, selectedIndex, candidate, normalize: ensureShape, onChanged: () => { markDirty(); renderAll(); } });
      if (!changed) setStatus(messages.rawJson.noChanges, 'ok');
    } catch (err) {
      setStatus(messages.rawJson.invalid(err.message), 'err');
    }
  };
}
