import { el, escapeHtml, requireEl, requireScopedEl, setStatus, syncButtonTooltip } from '../dom.js';
import { setDetailsSummary } from './detailsSummary.js';
export { renderDetailsSummaryHtml } from './detailsSummary.js';
import { clone, makeId, nextCategorySortValue } from '../config.js';
import { openModal, closeModal } from '../modals.js';
import { validateCategory } from '../validation.js';
import { renderBasicEditor } from './basicEditor.js';
import { renderItemOrderingEditor } from './itemOrderingEditor.js';
import { renderMatchingRulesEditor } from './matchingRulesEditor.js';
import { renderColorEditor } from './colorEditor.js';
import { renderRangeStateFiltersEditor } from './rangeStateFiltersEditor.js';
import { applySelectedCategoryCandidate, selectedCategoryStructuralFocusPlan } from '../categoryChanges.js';
import { textActionAvailable } from '../actionAvailability.js';
import { INT32_MAX, isSignedInt32Scalar } from '../filterScalars.js';

export { countRangeFilterIssues, countStateFilterIssues, rangeFiltersSummary, rangeFiltersSummaryParts, stateFiltersSummary, stateFiltersSummaryParts } from './filterSummary.js';
export { getBasicSwitchWarnings } from './basicEditor.js';

function createScheduledRenderList(renderList) {
  let scheduled = false;
  return () => {
    if (scheduled) return;
    scheduled = true;
    const flush = () => {
      scheduled = false;
      renderList();
    };
    if (typeof window !== 'undefined' && typeof window.requestAnimationFrame === 'function') {
      window.requestAnimationFrame(flush);
    } else {
      setTimeout(flush, 16);
    }
  };
}

export function renderEditor(deps) {
  const { getCategories, getSelectedIndex, setSelectedIndex, ensureShape, markDirty, markDirtyAndRenderList = () => markDirty({ renderList: true }), renderAll, renderList, renumberCategories, openRegexToItemIdsTool, listEditorDeps, lookupName, commitActiveField = () => {}, getEditorPreferences = () => ({ autoGenerateDescriptions: false }), copyTextToClipboard = async () => false, loadBasicPresets = null, loadAdvancedPresets = null } = deps;
  const scheduleRenderList = createScheduledRenderList(renderList);
  let selectedIndex = getSelectedIndex();
  const cats = getCategories();
  const root = requireEl('editor');
  root.innerHTML = '';

  if (!cats.length) {
    setSelectedIndex(-1); selectedIndex = -1;
    root.innerHTML = `
      <div class="card empty-state-card">
        <h2>No category selected</h2>
        <p class="hint">Start with:</p>
        <ul class="hint">
          <li><strong>Import/Paste</strong> or <strong>Upload</strong> to load an existing AetherBags export</li>
          <li><button id="loadBasicPresets" type="button" class="link-button" title="Import bundled basic preset categories" aria-label="Import bundled basic preset categories">Load basic presets</button></li>
          <li><button id="loadAdvancedPresets" type="button" class="link-button" title="Import bundled advanced preset categories" aria-label="Import bundled advanced preset categories">Load advanced presets</button></li>
          <li>Add a category manually</li>
        </ul>
        <p class="hint">Change appearance and other settings in Preferences.</p>
        <p class="hint">Click ? for more information about this app.</p>
      </div>`;
    const basicPresetButton = root.querySelector('#loadBasicPresets');
    if (basicPresetButton && typeof loadBasicPresets === 'function') basicPresetButton.addEventListener('click', () => { commitActiveField(); loadBasicPresets(); });
    const advancedPresetButton = root.querySelector('#loadAdvancedPresets');
    if (advancedPresetButton && typeof loadAdvancedPresets === 'function') advancedPresetButton.addEventListener('click', () => { commitActiveField(); loadAdvancedPresets(); });
    return;
  }
  if (selectedIndex < 0 || selectedIndex >= cats.length) { setSelectedIndex(0); selectedIndex = 0; }

  const cat = cats[selectedIndex];
  ensureShape(cat);

  const header = document.createElement('div');
  header.className = 'card';
  header.innerHTML = `
    <div class="row section-header-row">
      <div class="category-header-title">
        <div class="category-header-title-row">
          <h2 class="flush-heading">${escapeHtml(cat.Name || '(unnamed)')}</h2>
          <span class="ui-badge ui-badge-warning validation-badge category-validation-summary" hidden></span>
        </div>
      </div>
      <div class="row category-header-actions">
        <button id="moveUp" class="icon-button movement-button">↑</button>
        <button id="moveDown" class="icon-button movement-button">↓</button>
        <button id="duplicateCat" class="small">Duplicate</button>
        <button id="deleteCat" class="icon-button danger">🗑</button>
      </div>
    </div>
  `;
  root.appendChild(header);

  function updateHeaderTitle() {
    const title = requireScopedEl(header, '.flush-heading', 'category header');
    title.textContent = cat.Name || '(unnamed)';
  }

  function getCategoryIssueFindings(category = cat, allCategories = cats) {
    return validateCategory(category, allCategories).filter(item => item.severity === 'error' || item.severity === 'warning');
  }

  function updateCategoryIssueSummary() {
    const summary = requireScopedEl(header, '.category-validation-summary', 'category header');
    const findings = getCategoryIssueFindings();
    summary.hidden = findings.length === 0;
    summary.textContent = findings.length ? `${findings.length} validation ${findings.length === 1 ? 'issue' : 'issues'}` : '';
  }

  const basicEditor = renderBasicEditor(cat, {
    categories: cats,
    markDirty,
    markDirtyAndRenderList,
    renderList,
    onNameChanged: updateHeaderTitle,
    onCategoryValidationChanged: updateCategoryIssueSummary,
    lookupName,
    commitActiveField,
    getEditorPreferences,
    copyTextToClipboard
  });

  const topEditorGrid = document.createElement('div');
  topEditorGrid.className = 'top-editor-grid';
  const colorCard = renderColorEditor(cat, {
    markDirty,
    markDirtyAndRenderList,
    scheduleRenderList: createScheduledRenderList(renderList)
  });
  topEditorGrid.append(basicEditor.card, colorCard);
  root.appendChild(topEditorGrid);

  const itemOrdering = renderItemOrderingEditor(cat, {
    markDirty,
    renderList,
    listEditorDeps,
    onValidationChanged: basicEditor.refreshValidation,
    onOrderingChanged: () => basicEditor.maybeAutoGenerateDescription('item ordering changed'),
    openRawCategoryEditor: () => {
      const advanced = root.querySelector('details.advanced-category-card');
      const raw = advanced?.querySelector('#rawCategory');
      if (!advanced || !raw) return;
      advanced.open = true;
      raw.focus();
      raw.scrollIntoView({ block: 'nearest' });
    }
  });
  root.appendChild(itemOrdering);

  const rules = cat.Rules;
  root.appendChild(renderMatchingRulesEditor(cat, {
    categories: cats,
    markDirty,
    onRulesChanged: reason => {
      basicEditor.refreshValidation();
      basicEditor.maybeAutoGenerateDescription(reason);
      renderList();
    },
    openRegexToItemIdsTool,
    listEditorDeps
  }));

  const { ranges, states } = renderRangeStateFiltersEditor(rules, {
    markDirty,
    onFiltersChanged: reason => {
      updateCategoryIssueSummary();
      basicEditor.maybeAutoGenerateDescription(reason);
    },
    scheduleRenderList
  });
  root.append(ranges, states);

  const advanced = document.createElement('details');
  advanced.className = 'card advanced-category-card';
  advanced.innerHTML = `
    <summary></summary>
    <div class="details-body">
      <p class="hint">Edit the selected category directly. Click “Apply raw category JSON” after changes.</p>
      <textarea class="raw" id="rawCategory">${escapeHtml(JSON.stringify(cat, null, 2))}</textarea>
      <div class="row modal-action-row">
        <button id="applyRawCategory">Apply raw category JSON</button>
      </div>
    </div>
  `;
  setDetailsSummary(advanced, { title: 'Advanced', badges: [], issueCount: 0 });
  root.appendChild(advanced);

  const actionName = cat.Name || '(unnamed)';
  const actionLabels = {
    moveUp: `Move ${actionName} up`,
    moveDown: `Move ${actionName} down`,
    duplicateCat: `Duplicate ${actionName}`,
    deleteCat: `Delete ${actionName}`
  };
  el('moveUp').disabled = selectedIndex <= 0;
  el('moveDown').disabled = selectedIndex >= cats.length - 1;

  for (const [id, label] of Object.entries(actionLabels)) {
    const button = el(id);
    button.setAttribute('aria-label', label);
    syncButtonTooltip(button, label);
  }

  function restoreStructuralActionFocus(action) {
    for (const targetKey of selectedCategoryStructuralFocusPlan(action, selectedIndex, cats.length)) {
      const target = targetKey === 'selected-category'
        ? document.querySelector('.cat-item[aria-current="true"]')
        : el(targetKey);
      if (target && !target.disabled && !target.hidden && document.contains(target)) {
        target.focus();
        return true;
      }
    }
    return false;
  }

  el('moveUp').onclick = () => {
    commitActiveField();
    if (selectedIndex <= 0) return;
    [cats[selectedIndex - 1], cats[selectedIndex]] = [cats[selectedIndex], cats[selectedIndex - 1]];
    selectedIndex--; setSelectedIndex(selectedIndex);
    if (el('autoRenumberDrag').checked) renumberCategories();
    markDirty();
    renderAll();
    restoreStructuralActionFocus('move-up');
  };
  el('moveDown').onclick = () => {
    commitActiveField();
    if (selectedIndex >= cats.length - 1) return;
    [cats[selectedIndex + 1], cats[selectedIndex]] = [cats[selectedIndex], cats[selectedIndex + 1]];
    selectedIndex++; setSelectedIndex(selectedIndex);
    if (el('autoRenumberDrag').checked) renumberCategories();
    markDirty();
    renderAll();
    restoreStructuralActionFocus('move-down');
  };
  el('duplicateCat').onclick = () => {
    commitActiveField();
    const copy = clone(cat);
    copy.Id = makeId();
    copy.Name = (copy.Name || 'Category') + ' Copy';
    const nextSortValue = nextCategorySortValue(cats);
    const copyOrder = isSignedInt32Scalar(copy.Order) ? copy.Order : null;
    const copyPriority = isSignedInt32Scalar(copy.Priority) ? copy.Priority : null;
    if (copyOrder === null || copyPriority === null || copyOrder >= INT32_MAX || copyPriority >= INT32_MAX) {
      copy.Order = nextSortValue;
      copy.Priority = nextSortValue;
    } else {
      copy.Order = copyOrder + 1;
      copy.Priority = copyPriority + 1;
    }
    cats.splice(selectedIndex + 1, 0, copy);
    selectedIndex++; setSelectedIndex(selectedIndex);
    markDirty();
    renderAll();
    restoreStructuralActionFocus('duplicate');
  };
  el('deleteCat').onclick = () => {
    commitActiveField();
    const wrap = document.createElement('div');
    wrap.innerHTML = `
      <p>Delete <strong>${escapeHtml(cat.Name || '(unnamed)')}</strong>?</p>
      <p class="hint">This only affects the browser copy until you download or export.</p>
      <div class="row modal-action-row modal-action-row-loose">
        <button id="confirmDeleteCat" class="danger">Delete category</button>
        <button id="cancelDeleteCat">Cancel</button>
      </div>
    `;
    openModal('Delete category', wrap);
    requireScopedEl(wrap, '#confirmDeleteCat', 'delete category confirmation').onclick = () => {
      commitActiveField();
      cats.splice(selectedIndex, 1);
      selectedIndex = Math.min(selectedIndex, cats.length - 1); setSelectedIndex(selectedIndex);
      closeModal();
      markDirty();
      renderAll();
      restoreStructuralActionFocus('delete');
    };
    requireScopedEl(wrap, '#cancelDeleteCat', 'delete category confirmation').onclick = closeModal;
  };
  const rawCategory = el('rawCategory');
  const applyRawCategory = el('applyRawCategory');
  const syncRawCategoryAvailability = () => { applyRawCategory.disabled = !textActionAvailable(rawCategory.value); };
  syncRawCategoryAvailability();
  rawCategory.addEventListener('input', syncRawCategoryAvailability);
  applyRawCategory.onclick = () => {
    try {
      const candidate = JSON.parse(rawCategory.value);
      const changed = applySelectedCategoryCandidate({ categories: cats, selectedIndex, candidate, normalize: ensureShape, onChanged: () => { markDirty(); renderAll(); } });
      if (!changed) setStatus('There are no category changes to apply.', 'ok');
    } catch (err) {
      setStatus('Invalid category JSON: ' + err.message, 'err');
    }
  };
}
