import { openModal } from '../modals.js';

const HELP_SEMANTIC_ELEMENTS = Object.freeze({
  strong: 'strong',
  code: 'code'
});

const semantic = (kind, text) => ({ kind, text });
const strong = text => semantic('strong', text);
const code = text => semantic('code', text);

function textElement(documentRef, tagName, text) {
  const element = documentRef.createElement(tagName);
  element.textContent = text;
  return element;
}

export function appendHelpRichMessage(target, parts, documentRef = document) {
  for (const part of parts) {
    if (part.type === 'text') {
      target.appendChild(documentRef.createTextNode(part.value));
      continue;
    }
    if (part.type !== 'placeholder') {
      throw new Error(`Unknown rich-message part type: ${part.type}`);
    }
    const tagName = HELP_SEMANTIC_ELEMENTS[part.value?.kind];
    if (!tagName) {
      throw new Error(`Unsupported Help rich-message semantic: ${part.value?.kind}`);
    }
    const element = documentRef.createElement(tagName);
    element.textContent = part.value.text;
    target.appendChild(element);
  }
}

function richListItem(documentRef, translate, key, placeholders) {
  const item = documentRef.createElement('li');
  appendHelpRichMessage(item, translate.rich(key, placeholders), documentRef);
  return item;
}

function textListItem(documentRef, translate, key) {
  return textElement(documentRef, 'li', translate(key));
}

function appendSection(documentRef, wrap, translate, headingKey, items) {
  wrap.appendChild(textElement(documentRef, 'h3', translate(headingKey)));
  const list = documentRef.createElement('ul');
  list.append(...items);
  wrap.appendChild(list);
}

export function buildHelpContent(translate, documentRef = document) {
  const wrap = documentRef.createElement('div');
  wrap.className = 'help-modal';
  wrap.appendChild(textElement(documentRef, 'p', translate('help.introduction')));

  appendSection(documentRef, wrap, translate, 'help.workflow.title', [
    richListItem(documentRef, translate, 'help.workflow.import.message', {
      action: strong(translate('action.importPaste'))
    }),
    richListItem(documentRef, translate, 'help.workflow.upload.message', {
      action: strong(translate('action.upload'))
    }),
    richListItem(documentRef, translate, 'help.workflow.export.message', {
      action: strong(translate('action.exportCopy'))
    }),
    richListItem(documentRef, translate, 'help.workflow.download.message', {
      action: strong(translate('action.download')),
      extension: code('.txt')
    }),
    textListItem(documentRef, translate, 'help.workflow.reimport')
  ]);

  appendSection(documentRef, wrap, translate, 'help.lookup.title', [
    richListItem(documentRef, translate, 'help.lookup.resolveIds.message', {
      action: strong(translate('action.resolveIds'))
    }),
    richListItem(documentRef, translate, 'help.lookup.cache.message', {
      action: strong(translate('action.lookupCache'))
    }),
    richListItem(documentRef, translate, 'help.lookup.regex.message', {
      action: strong(translate('help.lookup.regex.label'))
    })
  ]);

  appendSection(documentRef, wrap, translate, 'help.preferences.title', [
    richListItem(documentRef, translate, 'help.preferences.preferences.message', {
      action: strong(translate('action.preferences'))
    }),
    richListItem(documentRef, translate, 'help.preferences.generate.message', {
      action: strong(translate('help.preferences.generate.label'))
    }),
    richListItem(documentRef, translate, 'help.preferences.behavior.message', {
      autoLookup: strong(translate('preferences.autoLookupImportedIds.label')),
      autoGenerate: strong(translate('preferences.autoGenerateDescriptions.label'))
    }),
    richListItem(documentRef, translate, 'help.preferences.storage.message', {
      storage: code('localStorage')
    })
  ]);

  appendSection(documentRef, wrap, translate, 'help.privacy.title', [
    textListItem(documentRef, translate, 'help.privacy.localProcessing'),
    richListItem(documentRef, translate, 'help.privacy.storage.message', {
      storage: code('localStorage')
    }),
    textListItem(documentRef, translate, 'help.privacy.xivapi'),
    textListItem(documentRef, translate, 'help.privacy.repository')
  ]);

  return wrap;
}

export function showHelpModal({ translate }) {
  openModal(translate('action.aboutHelp'), buildHelpContent(translate));
}
