import { escapeHtml, requireScopedEl } from '../dom.js';

const THEME_OPTIONS = [
  { value: 'system', label: 'System', hint: 'Follow your OS/browser color preference.' },
  { value: 'dark', label: 'Dark', hint: 'Neutral dark panels with a calm blue accent.' },
  { value: 'light', label: 'Light', hint: 'Simple light panels with readable dark text.' },
  { value: 'high-contrast', label: 'High Contrast', hint: 'Stronger contrast for improved readability.' },
  { value: 'aetherial', label: 'Aetherial', hint: 'Cool luminous blues, cyan, and violet.' },
  { value: 'dalamud', label: 'Dalamud', hint: 'Restrained plugin-panel charcoal, purple, and warm red tones.' }
];

const DENSITY_OPTIONS = [
  { value: 'comfortable', label: 'Comfortable', hint: 'Current spacing and relaxed layout.' },
  { value: 'compact', label: 'Compact', hint: 'Tighter cards, groups, and controls while keeping hit targets usable.' }
];

function preferenceCheckbox(id, label, checked, hint) {
  const wrap = document.createElement('label');
  wrap.className = 'check preference-check';
  wrap.innerHTML = `
    <input id="${escapeHtml(id)}" type="checkbox" ${checked ? 'checked' : ''}>
    <span><strong>${escapeHtml(label)}</strong><br><span class="hint">${escapeHtml(hint)}</span></span>
  `;
  return wrap;
}

function preferenceSelect(id, label, value, options) {
  const wrap = document.createElement('div');
  wrap.innerHTML = `
    <label for="${escapeHtml(id)}">${escapeHtml(label)}</label>
    <select id="${escapeHtml(id)}">
      ${options.map(option => `<option value="${escapeHtml(option.value)}">${escapeHtml(option.label)}</option>`).join('')}
    </select>
    <p class="hint">${escapeHtml(options.find(option => option.value === value)?.hint || '')}</p>
  `;
  requireScopedEl(wrap, 'select', 'appearance preference select').value = value;
  return wrap;
}

function setActiveTab(wrap, tabName) {
  for (const button of wrap.querySelectorAll('[role="tab"]')) {
    const selected = button.dataset.tab === tabName;
    button.setAttribute('aria-selected', selected ? 'true' : 'false');
    button.setAttribute('tabindex', selected ? '0' : '-1');
    button.classList.toggle('active', selected);
  }
  for (const panel of wrap.querySelectorAll('[role="tabpanel"]')) {
    panel.hidden = panel.dataset.panel !== tabName;
  }
}

export function showPreferencesModal({ getEditorPreferences, applyEditorPreferences, setStatus, openModal, commitActiveField }) {
  commitActiveField();
  let preferences = getEditorPreferences();
  const wrap = document.createElement('div');
  wrap.className = 'preferences-modal';
  wrap.innerHTML = `
    <p class="hint">These editor preferences are stored locally in this browser only. They affect the editor UI and are never included in exported AetherBags category data.</p>
    <div class="preferences-tabs" role="tablist" aria-label="Preference sections">
      <button id="appearancePreferencesTab" class="small active" type="button" role="tab" aria-selected="true" tabindex="0" aria-controls="appearancePreferencesPanel" data-tab="appearance">Appearance</button>
      <button id="behaviorPreferencesTab" class="small" type="button" role="tab" aria-selected="false" tabindex="-1" aria-controls="behaviorPreferencesPanel" data-tab="behavior">Behavior</button>
    </div>
    <section id="appearancePreferencesPanel" role="tabpanel" aria-labelledby="appearancePreferencesTab" data-panel="appearance">
      <h3>Appearance</h3>
      <div class="grid cols-2" id="appearancePreferenceGrid"></div>
    </section>
    <section id="behaviorPreferencesPanel" role="tabpanel" aria-labelledby="behaviorPreferencesTab" data-panel="behavior" hidden>
      <h3>Behavior</h3>
      <div id="behaviorPreferenceGrid" class="grid"></div>
    </section>
  `;
  const grid = requireScopedEl(wrap, '#appearancePreferenceGrid', 'Appearance preferences');
  grid.append(
    preferenceSelect('themePreference', 'Theme', preferences.theme, THEME_OPTIONS),
    preferenceSelect('densityPreference', 'Density', preferences.density, DENSITY_OPTIONS)
  );
  const behaviorGrid = requireScopedEl(wrap, '#behaviorPreferenceGrid', 'Behavior preferences');
  behaviorGrid.append(
    preferenceCheckbox('autoLookupImportedIdsPreference', 'Auto-lookup imported IDs', preferences.autoLookupImportedIds, 'After import, automatically resolve uncached referenced item and UI category names.'),
    preferenceCheckbox('autoGenerateDescriptionsPreference', 'Auto-generate descriptions', preferences.autoGenerateDescriptions, 'When enabled, new or edited blank descriptions may be filled from the category name and selected rules. Existing descriptions are never overwritten.')
  );

  openModal('Editor Preferences', wrap);

  const tabs = [...wrap.querySelectorAll('[role="tab"]')];
  function moveTabFocus(index) {
    const nextTab = tabs[(index + tabs.length) % tabs.length];
    setActiveTab(wrap, nextTab.dataset.tab);
    nextTab.focus();
  }

  for (const [index, tab] of tabs.entries()) {
    tab.addEventListener('click', () => setActiveTab(wrap, tab.dataset.tab));
    tab.addEventListener('keydown', e => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        moveTabFocus(index + 1);
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        moveTabFocus(index - 1);
      } else if (e.key === 'Home') {
        e.preventDefault();
        moveTabFocus(0);
      } else if (e.key === 'End') {
        e.preventDefault();
        moveTabFocus(tabs.length - 1);
      }
    });
  }

  const bindSelect = (id, key) => {
    const select = requireScopedEl(wrap, `#${id}`, 'Appearance preferences');
    select.addEventListener('change', e => {
      preferences = applyEditorPreferences({ ...getEditorPreferences(), [key]: e.target.value });
      setStatus('Editor preferences saved locally.', 'ok');
    });
  };

  const bindCheckbox = (id, key) => {
    requireScopedEl(wrap, `#${id}`, 'Behavior preferences').addEventListener('change', e => {
      preferences = applyEditorPreferences({ ...getEditorPreferences(), [key]: e.target.checked });
      setStatus('Editor preferences saved locally.', 'ok');
    });
  };

  bindSelect('themePreference', 'theme');
  bindSelect('densityPreference', 'density');
  bindCheckbox('autoLookupImportedIdsPreference', 'autoLookupImportedIds');
  bindCheckbox('autoGenerateDescriptionsPreference', 'autoGenerateDescriptions');
}
