import { escapeHtml, requireScopedEl } from '../dom.js';

const THEME_OPTIONS = [
  { value: 'system', key: 'system' },
  { value: 'dark', key: 'dark' },
  { value: 'light', key: 'light' },
  { value: 'high-contrast', key: 'highContrast' },
  { value: 'aetherial', key: 'aetherial' },
  { value: 'dalamud', key: 'dalamud' }
];

const DENSITY_OPTIONS = [
  { value: 'comfortable', key: 'comfortable' },
  { value: 'compact', key: 'compact' }
];

function preferenceCheckbox(id, label, checked, hint) {
  const wrap = document.createElement('label');
  wrap.className = 'check preference-check';
  wrap.innerHTML = `
    <input id="${escapeHtml(id)}" type="checkbox" ${checked ? 'checked' : ''}>
    <span><strong>${escapeHtml(label)}</strong><br><span class="hint">${escapeHtml(hint)}</span></span>
  `;
  return wrap;
}

function preferenceSelect(id, label, value, options, translate, keyPrefix) {
  const wrap = document.createElement('div');
  wrap.innerHTML = `
    <label for="${escapeHtml(id)}">${escapeHtml(label)}</label>
    <select id="${escapeHtml(id)}">
      ${options.map(option => `<option value="${escapeHtml(option.value)}">${escapeHtml(translate(`${keyPrefix}.${option.key}.label`))}</option>`).join('')}
    </select>
    <p class="hint">${escapeHtml(translate(`${keyPrefix}.${options.find(option => option.value === value)?.key}.hint`))}</p>
  `;
  requireScopedEl(wrap, 'select', 'appearance preference select').value = value;
  return wrap;
}

function setActiveTab(wrap, tabName) {
  for (const button of wrap.querySelectorAll('[role="tab"]')) {
    const selected = button.dataset.tab === tabName;
    button.setAttribute('aria-selected', selected ? 'true' : 'false');
    button.setAttribute('tabindex', selected ? '0' : '-1');
    button.classList.toggle('active', selected);
  }
  for (const panel of wrap.querySelectorAll('[role="tabpanel"]')) {
    panel.hidden = panel.dataset.panel !== tabName;
  }
}

export function showPreferencesModal({ getEditorPreferences, applyEditorPreferences, setStatus, openModal, commitActiveField, translate }) {
  commitActiveField();
  let preferences = getEditorPreferences();
  const wrap = document.createElement('div');
  wrap.className = 'preferences-modal';
  wrap.innerHTML = `
    <p class="hint">${escapeHtml(translate('preferences.introduction'))}</p>
    <div class="preferences-tabs" role="tablist" aria-label="${escapeHtml(translate('preferences.sections.label'))}">
      <button id="appearancePreferencesTab" class="small active" type="button" role="tab" aria-selected="true" tabindex="0" aria-controls="appearancePreferencesPanel" data-tab="appearance">${escapeHtml(translate('preferences.appearance.title'))}</button>
      <button id="behaviorPreferencesTab" class="small" type="button" role="tab" aria-selected="false" tabindex="-1" aria-controls="behaviorPreferencesPanel" data-tab="behavior">${escapeHtml(translate('preferences.behavior.title'))}</button>
    </div>
    <section id="appearancePreferencesPanel" role="tabpanel" aria-labelledby="appearancePreferencesTab" data-panel="appearance">
      <h3>${escapeHtml(translate('preferences.appearance.title'))}</h3>
      <div class="grid cols-2" id="appearancePreferenceGrid"></div>
    </section>
    <section id="behaviorPreferencesPanel" role="tabpanel" aria-labelledby="behaviorPreferencesTab" data-panel="behavior" hidden>
      <h3>${escapeHtml(translate('preferences.behavior.title'))}</h3>
      <div id="behaviorPreferenceGrid" class="grid"></div>
    </section>
  `;
  const grid = requireScopedEl(wrap, '#appearancePreferenceGrid', 'Appearance preferences');
  grid.append(
    preferenceSelect('themePreference', translate('preferences.theme.label'), preferences.theme, THEME_OPTIONS, translate, 'preferences.theme'),
    preferenceSelect('densityPreference', translate('preferences.density.label'), preferences.density, DENSITY_OPTIONS, translate, 'preferences.density')
  );
  const behaviorGrid = requireScopedEl(wrap, '#behaviorPreferenceGrid', 'Behavior preferences');
  behaviorGrid.append(
    preferenceCheckbox('autoLookupImportedIdsPreference', translate('preferences.autoLookupImportedIds.label'), preferences.autoLookupImportedIds, translate('preferences.autoLookupImportedIds.hint')),
    preferenceCheckbox('autoGenerateDescriptionsPreference', translate('preferences.autoGenerateDescriptions.label'), preferences.autoGenerateDescriptions, translate('preferences.autoGenerateDescriptions.hint'))
  );

  openModal(translate('preferences.title'), wrap);

  const tabs = [...wrap.querySelectorAll('[role="tab"]')];
  function moveTabFocus(index) {
    const nextTab = tabs[(index + tabs.length) % tabs.length];
    setActiveTab(wrap, nextTab.dataset.tab);
    nextTab.focus();
  }

  for (const [index, tab] of tabs.entries()) {
    tab.addEventListener('click', () => setActiveTab(wrap, tab.dataset.tab));
    tab.addEventListener('keydown', e => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        moveTabFocus(index + 1);
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        moveTabFocus(index - 1);
      } else if (e.key === 'Home') {
        e.preventDefault();
        moveTabFocus(0);
      } else if (e.key === 'End') {
        e.preventDefault();
        moveTabFocus(tabs.length - 1);
      }
    });
  }

  const bindSelect = (id, key) => {
    const select = requireScopedEl(wrap, `#${id}`, 'Appearance preferences');
    select.addEventListener('change', e => {
      preferences = applyEditorPreferences({ ...getEditorPreferences(), [key]: e.target.value });
      setStatus(translate('preferences.saved'), 'ok');
    });
  };

  const bindCheckbox = (id, key) => {
    requireScopedEl(wrap, `#${id}`, 'Behavior preferences').addEventListener('change', e => {
      preferences = applyEditorPreferences({ ...getEditorPreferences(), [key]: e.target.checked });
      setStatus(translate('preferences.saved'), 'ok');
    });
  };

  bindSelect('themePreference', 'theme');
  bindSelect('densityPreference', 'density');
  bindCheckbox('autoLookupImportedIdsPreference', 'autoLookupImportedIds');
  bindCheckbox('autoGenerateDescriptionsPreference', 'autoGenerateDescriptions');
}
