import { INITIAL_DATA, LOOKUP_BATCH_SIZE } from './constants.js';
import { el, bindChange, bindClick, bindInput, escapeHtml, requireEl, requireScopedEl, setSaveState, setStatus, showBusy, updateBusy, hideBusy } from './dom.js';
import { loadLookupCache, persistLookupCache, removeLookupCache, emptyLookupCache, loadEditorPreferences, persistEditorPreferences } from './state.js';
import { defaultCategory as makeDefaultCategory, ensureShape, validateConfig, compareCategoriesForImport, nextCategorySortValue } from './config.js';
import { openModal, closeModal, isModalOpen, trapModalFocus } from './modals.js';
import { renderCategoryList } from './ui/categoryList.js';
import { renderEditor as renderCategoryEditor } from './ui/categoryEditor.js';
import { showHelpModal } from './ui/helpModal.js';
import { showLookupCacheModal } from './ui/lookupCacheModal.js';
import { showPreferencesModal } from './ui/preferencesModal.js';
import { applyApplicationChromeLocalization } from './ui/applicationChrome.js';
import { createTranslator } from './localization.js';
import { openRegexToItemIdsTool as openRegexTool } from './tools/regexToItemIds.js';
import { EXPORT_FILENAME, assertJsonTextWithinLimit, copyTextToClipboard, downloadText, makeBase64Export, parseImportedText, parseJsonText, readImportFileText } from './importExport.js';
import { sheetLabel, collectReferencedIds, countReferencedIds, countUncachedReferencedIds, fetchLookupBatch as xivapiFetchLookupBatch, searchXivapi } from './xivapi.js';
import { generateCategoryDescription, isUsefulGeneratedDescription } from './descriptionGenerator.js';
import { isUsefulLookupName } from './lookupNames.js';
import { analyzeImportedConfig, mergeValidationFindings } from './validation.js';
import { PRESETS } from './presets.js';
import { createLookupCacheOperationCoordinator, clearLookupCacheIfIdle } from './lookupCacheOperations.js';
import { applyConfigReplacement, applyFullConfigCandidate, renumberCategories as applyCategoryRenumber, sortCategoriesPreservingSelection } from './categoryChanges.js';
import { isSnapshotCurrent, makeRevisionedExportSnapshot, saveSnapshotIfCurrent } from './exportSnapshots.js';
import { runAetherBagsExportPreflight } from './exportCompatibility.js';
import { categoryRenumberAvailable, categorySortAvailable, referencedIdLookupAvailable, textActionAvailable } from './actionAvailability.js';
import {
  reviewableImportRepairs,
  reviewableImportFindings,
  shouldShowImportValidationModal,
  configValidationSummaryText,
  validationSummaryText,
  importStatusSeverity
} from './importValidationSummary.js';


let data = JSON.parse(JSON.stringify(INITIAL_DATA));
let selectedIndex = -1;
let dirty = false;
let dataRevision = 0;
let draggedIndex = null;
let lookupCache = loadLookupCache();
let editorPreferences = loadEditorPreferences();
const translate = createTranslator('en');
const lookupCacheOperations = createLookupCacheOperationCoordinator();
let resolvingReferencedIds = false;

function applyEditorPreferences(preferences = editorPreferences) {
  editorPreferences = persistEditorPreferences(preferences);
  const root = document.documentElement;
  root.dataset.theme = editorPreferences.theme;
  root.dataset.density = editorPreferences.density;
  return editorPreferences;
}

function saveLookupCache() { persistLookupCache(lookupCache); }
function lookupCacheStats(sheet) {
  const values = Object.values(lookupCache[sheet] || {});
  const useful = values.filter(isUsefulLookupName).length;
  return { useful, unresolved: values.length - useful, total: values.length };
}
function lookupName(sheet, id) { const cache = lookupCache[sheet] || {}; return cache[String(id)] || null; }
function fetchLookupBatch(sheet, ids, options = {}) { return xivapiFetchLookupBatch(sheet, ids, { ...options, lookupCache, saveLookupCache }); }
function clearLookupCache() {
  return clearLookupCacheIfIdle({
    isActive: lookupCacheOperations.isActive,
    onRefused: () => setStatus('Lookup cache cannot be cleared while a lookup or scan is running.', 'warn'),
    clear: () => { lookupCache = emptyLookupCache(); removeLookupCache(); renderAll(); setStatus('Lookup cache cleared. Category data was not changed.', 'ok'); }
  });
}
function getCategories() { return data.Categories; }
function defaultCategory() {
  const category = makeDefaultCategory(nextCategorySortValue(getCategories()) - 1);
  if (editorPreferences.autoGenerateDescriptions) {
    const generated = generateCategoryDescription(category, { lookupName });
    if (isUsefulGeneratedDescription(generated)) category.Description = generated;
  }
  return category;
}
function renumberCategories() { return applyCategoryRenumber(getCategories()); }
function advanceDataRevision() { dataRevision += 1; }
function markDirty(options = {}) {
  advanceDataRevision();
  dirty = true;
  setSaveState('Changes not exported', 'warn');
  if (options.renderList) renderList();
}
function markDirtyAndRenderList() { markDirty({ renderList: true }); }
function markSaved(label='Exported') { dirty = false; setSaveState(label); }
function applyValidatedConfig(validation) {
  return applyConfigReplacement(data, validation.config, candidate => {
    data = candidate;
    advanceDataRevision();
  });
}

function shortRepairValue(value) {
  const text = JSON.stringify(value);
  if (text === undefined) return String(value);
  return text.length > 120 ? `${text.slice(0, 117)}…` : text;
}

function repairFieldAllowsBeforeAfter(field) {
  return field === 'AllowedRarities'
    || field === 'Level'
    || field === 'ItemLevel'
    || field === 'VendorPrice'
    || field === 'Untradable'
    || field === 'Unique'
    || field === 'Collectable'
    || field === 'Dyeable'
    || field === 'Repairable'
    || field === 'HighQuality'
    || field === 'Desynthesizable'
    || field === 'Glamourable'
    || field === 'FullySpiritbonded';
}

function formatRepairMessage(repair) {
  const prefix = repair.categoryName ? `“${repair.categoryName}”: ` : '';
  const canShowBeforeAfter = repair.showBeforeAfter !== false && repairFieldAllowsBeforeAfter(repair.field);
  if (canShowBeforeAfter && (repair.before !== undefined || repair.after !== undefined)) {
    return `${prefix}${repair.message} Changed from ${shortRepairValue(repair.before)} to ${shortRepairValue(repair.after)}.`;
  }
  return `${prefix}${repair.message}`;
}

function showValidationSummary(title, analysis, repairs = []) {
  const reviewFindings = reviewableImportFindings(analysis.findings || []);
  const reviewRepairs = reviewableImportRepairs(repairs);
  if (!reviewFindings.length && !reviewRepairs.length) return;
  const wrap = document.createElement('div');
  const rows = reviewFindings.slice(0, 80).map(item => `<li class="field-${item.severity}"><strong>${escapeHtml(item.severity)}:</strong> ${escapeHtml(item.categoryName ? `${item.categoryName} · ${item.field}` : item.field)} — ${escapeHtml(item.message)}</li>`).join('');
  const more = reviewFindings.length > 80 ? `<p class="hint">Showing first 80 of ${reviewFindings.length} findings.</p>` : '';
  const findingsSection = reviewFindings.length ? `<ul class="validation-list">${rows}</ul>${more}` : '<p class="hint">No validation guardrail findings.</p>';
  const repairRows = reviewRepairs.slice(0, 80).map(repair => `<li>${escapeHtml(formatRepairMessage(repair))}</li>`).join('');
  const repairMore = reviewRepairs.length > 80 ? `<p class="hint">Showing first 80 of ${reviewRepairs.length} import changes.</p>` : '';
  const repairSection = reviewRepairs.length ? `<h3>Changes made during import</h3><ul class="validation-list">${repairRows}</ul>${repairMore}` : '';
  wrap.innerHTML = `<p class="hint">Warnings and import repairs do not block import; they are shown so you can review meaningful cleanup.</p>${findingsSection}${repairSection}<div class="row modal-action-row"><button id="closeValidationSummary" class="primary">Continue editing</button></div>`;
  openModal(title, wrap);
  try { requireScopedEl(wrap, '#closeValidationSummary', 'validation summary').addEventListener('click', closeModal); } catch (err) { reportModalBindingError('Validation summary unavailable', err); }
}

function showExportCompatibilitySummary(decision) {
  const findings = decision.blockingFindings || [];
  const rows = findings.slice(0, 80).map(item => {
    const location = item.categoryName ? `${item.categoryName} · ${item.field}` : item.field;
    return `<li class="field-error"><strong>${escapeHtml(location)}:</strong> ${escapeHtml(item.message)}</li>`;
  }).join('');
  const more = findings.length > 80 ? `<p class="hint">Showing first 80 of ${findings.length} blocking compatibility errors.</p>` : '';
  const wrap = document.createElement('div');
  wrap.innerHTML = `<div role="alert"><p><strong>Export blocked:</strong> the current data contains ${findings.length} value(s) that cannot be safely serialized or read by the current AetherBags category importer.</p><p class="hint">Correct the listed fields in the structured controls or Raw JSON, then run Export / Copy or Download again. Values that AetherBags will safely default or ignore are review warnings and do not block export. No export was generated and the saved state was not changed.</p></div><ul class="validation-list">${rows}</ul>${more}<div class="row modal-action-row"><button id="closeExportCompatibility" class="primary">Continue editing</button></div>`;
  openModal('AetherBags export compatibility', wrap);
  try { requireScopedEl(wrap, '#closeExportCompatibility', 'export compatibility').addEventListener('click', closeModal); }
  catch (err) { reportModalBindingError('Export compatibility summary unavailable', err); }
  setStatus(`Export blocked by ${findings.length} AetherBags compatibility error(s). Correct the listed fields and try again.`, 'err');
}

async function makeCompatibleRevisionedExportSnapshot(busyTitle, busyMessage, onBusy = () => {}) {
  const result = await runAetherBagsExportPreflight(data, async () => {
    onBusy();
    showBusy(busyTitle, busyMessage, null);
    return makeRevisionedExportSnapshot(data, () => dataRevision, makeBase64Export);
  });
  if (!result.allowed) {
    showExportCompatibilitySummary(result);
    return null;
  }
  return result.value;
}
function openRegexToItemIdsTool() { commitActiveField(); openRegexTool({ getCategories, getSelectedIndex: () => selectedIndex, ensureShape, lookupCache, saveLookupCache, acquireLookupCacheProducer: lookupCacheOperations.acquire, markDirty, renderAll, onAvailabilityChanged: updateGlobalActionAvailability }); }

function commitActiveField() {
  const active = document.activeElement;
  if (!active || active === document.body || !document.contains(active)) return;
  const tag = active.tagName ? active.tagName.toLowerCase() : '';
  const editable = tag === 'input' || tag === 'select' || tag === 'textarea' || active.isContentEditable;
  if (editable && typeof active.blur === 'function') active.blur();
}

function setInlineError(id, message) {
  const node = el(id);
  if (!node) return;
  node.textContent = message || '';
  node.classList.toggle('hidden', !message);
}

function errorMessage(prefix, err) {
  const message = err instanceof Error ? err.message : String(err);
  return `${prefix}: ${message}`;
}


function reportModalBindingError(context, err) {
  setStatus(`${context}: ${err instanceof Error ? err.message : String(err)}`, 'err');
}

function confirmReplacingCurrentWork() {
  if (!dirty) return Promise.resolve(true);
  const wrap = document.createElement('div');
  wrap.innerHTML = `<p class="hint">Current unexported changes will be replaced. Export or download them first if you want to keep them.</p><div class="row modal-action-row"><button id="confirmReplaceWork" class="danger">Replace current data</button><button id="cancelReplaceWork">Cancel</button></div>`;
  return new Promise(resolve => {
    let confirmed = false;
    openModal('Replace current data?', wrap, { onClose: () => resolve(confirmed) });
    try {
      requireScopedEl(wrap, '#confirmReplaceWork', 'replace confirmation').addEventListener('click', () => { confirmed = true; closeModal(); });
      requireScopedEl(wrap, '#cancelReplaceWork', 'replace confirmation').addEventListener('click', () => closeModal());
    } catch (err) {
      reportModalBindingError('Replace confirmation unavailable', err);
    }
  });
}

function updateExportControls() {
  const disabled = getCategories().length === 0;
  for (const id of ['showExportCopy', 'downloadBase64']) {
    const button = el(id);
    if (!button) continue;
    button.disabled = disabled;
    button.removeAttribute('title');
  }
}

function updateGlobalActionAvailability() {
  const categories = getCategories();
  const sortButton = el('sortByOrder');
  const renumberButton = el('renumber');
  const lookupButton = el('lookupReferencedIds');
  if (sortButton) sortButton.disabled = !categorySortAvailable(categories, compareCategoriesForImport);
  if (renumberButton) renumberButton.disabled = !categoryRenumberAvailable(categories);
  if (lookupButton) {
    const ids = collectReferencedIds(categories, ensureShape);
    const uncached = countUncachedReferencedIds(ids, lookupName);
    lookupButton.disabled = !referencedIdLookupAvailable(uncached, resolvingReferencedIds);
  }
}

function renderList() {
  renderCategoryList({
    data, getCategories, ensureShape,
    getSelectedIndex: () => selectedIndex,
    setSelectedIndex: value => { selectedIndex = value; },
    getDraggedIndex: () => draggedIndex,
    setDraggedIndex: value => { draggedIndex = value; },
    renumberCategories, markDirty: markDirtyAndRenderList, renderAll, commitActiveField
  });
  updateGlobalActionAvailability();
}

function loadPreset(preset) {
  if (!preset?.data) {
    setStatus('Preset is not available.', 'err');
    return false;
  }
  return importText(preset.data, preset.sourceLabel || 'Preset');
}

function loadBasicPresets() {
  return loadPreset(PRESETS.find(preset => preset.id === 'basic'));
}

function loadAdvancedPresets() {
  return loadPreset(PRESETS.find(preset => preset.id === 'advanced'));
}

function renderEditor() {
  renderCategoryEditor({
    getCategories,
    getSelectedIndex: () => selectedIndex,
    setSelectedIndex: value => { selectedIndex = value; },
    ensureShape, markDirty, markDirtyAndRenderList, renderAll, renderList, renumberCategories, openRegexToItemIdsTool, lookupName, commitActiveField, getEditorPreferences: () => editorPreferences, copyTextToClipboard, loadBasicPresets, loadAdvancedPresets,
    listEditorDeps: { lookupName, fetchLookupBatch, searchXivapi, lookupCache, saveLookupCache, acquireLookupCacheProducer: lookupCacheOperations.acquire, markDirty, onAvailabilityChanged: updateGlobalActionAvailability }
  });
}

// Use renderAll only for structural changes; local field edits should update local UI/list instead.
function renderAll() { renderList(); renderEditor(); updateExportControls(); updateGlobalActionAvailability(); }

async function lookupReferencedIds(options = {}) {
  const { quiet = false } = options;
  const ids = collectReferencedIds(getCategories(), ensureShape);
  const total = countReferencedIds(ids);
  const uncached = countUncachedReferencedIds(ids, lookupName);
  if (!total) { if (!quiet) setStatus('No referenced Item/UI Category IDs to look up.', 'warn'); return; }
  if (!uncached) { if (!quiet) setStatus(`All ${total} referenced ID name(s) already cached.`, 'ok'); commitActiveField(); renderAll(); return; }
  resolvingReferencedIds = true;
  updateGlobalActionAvailability();
  const failures = [];
  const releaseLookupCacheProducer = lookupCacheOperations.acquire();
  try {
    showBusy('Looking up IDs', `0/${uncached} complete`, 0);
    for (const [sheet, sheetIds] of [['ItemUICategory', [...ids.ItemUICategory]], ['Item', [...ids.Item]]]) {
      const missing = sheetIds.filter(id => !isUsefulLookupName(lookupName(sheet, id)));
      if (!missing.length) continue;
      const priorCached = uncached - countUncachedReferencedIds(ids, lookupName);
      const batchFailures = await fetchLookupBatch(sheet, missing, { onProgress(doneForSheet, totalForSheet) { const done = Math.min(uncached, priorCached + doneForSheet); const percent = uncached ? (done / uncached) * 100 : 100; updateBusy(`${done}/${uncached} checked · ${sheetLabel(sheet)} batch ${Math.ceil(doneForSheet / LOOKUP_BATCH_SIZE)}/${Math.ceil(totalForSheet / LOOKUP_BATCH_SIZE)}`, percent); } });
      failures.push(...batchFailures.map(failure => `${failure.sheet} ${failure.id}`));
    }
    saveLookupCache(); commitActiveField(); renderAll();
    if (failures.length) {
      const shown = failures.slice(0, 5).join(', ');
      const more = failures.length > 5 ? `, +${failures.length - 5} more` : '';
      const message = `Lookup finished with ${failures.length} failure(s): ${shown}${more}`;
      if (quiet) setStatus(`Automatic lookup left ${failures.length} unresolved ID(s).`);
      else setStatus(message, 'warn');
    }
    else if (quiet) setStatus(`Automatic lookup cached ${uncached} new name(s).`);
    else setStatus(`Lookup complete: ${uncached} new name(s) cached.`, 'ok');
  } finally { releaseLookupCacheProducer(); hideBusy(); resolvingReferencedIds = false; updateGlobalActionAvailability(); }
}

function maybeAutoLookupImportedIds() {
  if (!editorPreferences.autoLookupImportedIds) return;
  lookupReferencedIds({ quiet: true }).catch(err => { setStatus(errorMessage('Automatic ID lookup failed', err), 'warn'); });
}

async function importText(text, sourceLabel='Import') {
  const parsed = await parseImportedText(text);
  const preAnalysis = analyzeImportedConfig(parsed);
  const validation = validateConfig(parsed);
  const postAnalysis = analyzeImportedConfig(validation.config);
  const importAnalysis = mergeValidationFindings(preAnalysis, postAnalysis);
  if (!(await confirmReplacingCurrentWork())) return false;
  applyValidatedConfig(validation);
  selectedIndex = getCategories().length ? 0 : -1;
  markSaved('No changes');
  const guardrailSummary = validationSummaryText(getCategories().length, importAnalysis, validation.repairs || []);
  setStatus(sourceLabel ? `${sourceLabel}: ${guardrailSummary}` : guardrailSummary, importStatusSeverity(importAnalysis, validation.repairs || []));
  commitActiveField();
  renderAll();
  if (shouldShowImportValidationModal({ analysis: importAnalysis, repairs: validation.repairs || [] })) setTimeout(() => showValidationSummary('Import validation summary', importAnalysis, validation.repairs || []), 0);
  maybeAutoLookupImportedIds();
  return true;
}

function showImportModal(initialText = '') {
  commitActiveField();
  const wrap = document.createElement('div');
  wrap.innerHTML = `<p class="hint">Paste either formatted JSON or the gzip+Base64 blob. Then click Import.</p><div id="importError" class="modal-error hidden" role="alert"></div><textarea id="importText" class="raw" placeholder="Paste JSON or gzip+Base64 here">${escapeHtml(initialText)}</textarea><div class="row modal-action-row"><button id="importNow" class="primary">Import</button></div>`;
  openModal('Import / Paste', wrap);
  try {
    const importTextNode = requireScopedEl(wrap, '#importText', 'import');
    const importButton = requireScopedEl(wrap, '#importNow', 'import');
    const syncImportAvailability = () => { importButton.disabled = !textActionAvailable(importTextNode.value); };
    syncImportAvailability();
    importTextNode.addEventListener('input', syncImportAvailability);
    importButton.addEventListener('click', async () => {
      commitActiveField();
      const text = importTextNode.value;
      try {
        setInlineError('importError', '');
        if (!(await importText(text, ''))) { showImportModal(text); return; }
        closeModal();
      } catch (err) { const message = errorMessage('Import failed', err); setInlineError('importError', message); setStatus(message, 'err'); }
    });
  } catch (err) {
    reportModalBindingError('Import unavailable', err);
  }
}

function showRawModal(initialText = JSON.stringify(data, null, 2), initialError = '') {
  commitActiveField();
  const wrap = document.createElement('div');
  wrap.innerHTML = `<p class="hint">This is the full JSON config. Edit carefully; invalid JSON cannot be applied.</p><div id="rawError" class="modal-error hidden" role="alert"></div><textarea id="rawFull" class="raw">${escapeHtml(initialText)}</textarea><div class="row modal-action-row"><button id="applyRawFull" class="primary">Apply full JSON</button><button id="copyRawFull">Copy</button></div><p class="hint" id="rawCopyStatus"></p>`;
  openModal('Raw JSON', wrap);
  setInlineError('rawError', initialError);
  try {
    const rawFull = requireScopedEl(wrap, '#rawFull', 'raw JSON');
    const rawCopyStatus = requireScopedEl(wrap, '#rawCopyStatus', 'raw JSON');
    const applyRawFull = requireScopedEl(wrap, '#applyRawFull', 'raw JSON');
    const copyRawFull = requireScopedEl(wrap, '#copyRawFull', 'raw JSON');
    const syncRawAvailability = () => {
      const available = textActionAvailable(rawFull.value);
      applyRawFull.disabled = !available;
      copyRawFull.disabled = !available;
    };
    syncRawAvailability();
    rawFull.addEventListener('input', syncRawAvailability);
    applyRawFull.addEventListener('click', async () => {
      commitActiveField();
      const text = rawFull.value;
      let validation;
      let preAnalysis;
      try { const parsed = parseJsonText(text, { label: 'Full Raw JSON input' }); preAnalysis = analyzeImportedConfig(parsed); validation = validateConfig(parsed); }
      catch (err) { const message = errorMessage('Invalid full JSON', err); setInlineError('rawError', message); setStatus(message, 'err'); return; }
      setInlineError('rawError', '');
      const rawAnalysis = mergeValidationFindings(preAnalysis, analyzeImportedConfig(validation.config));
      const rawSummary = configValidationSummaryText(validation.config, rawAnalysis, validation.repairs || []);
      const showRawSummary = () => {
        setStatus(rawSummary, importStatusSeverity(rawAnalysis, validation.repairs || []));
        if (shouldShowImportValidationModal({ analysis: rawAnalysis, repairs: validation.repairs || [] })) setTimeout(() => showValidationSummary('Raw JSON validation summary', rawAnalysis, validation.repairs || []), 0);
      };
      const result = await applyFullConfigCandidate({
        currentData: data,
        candidate: validation.config,
        confirmReplace: confirmReplacingCurrentWork,
        onNoChange: () => {
          closeModal();
          setStatus(`${rawSummary} No full JSON changes were applied.`, importStatusSeverity(rawAnalysis, validation.repairs || []));
          if (shouldShowImportValidationModal({ analysis: rawAnalysis, repairs: validation.repairs || [] })) setTimeout(() => showValidationSummary('Raw JSON validation summary', rawAnalysis, validation.repairs || []), 0);
        },
        onChanged: () => {
          applyValidatedConfig(validation);
          selectedIndex = getCategories().length ? 0 : -1;
          closeModal();
          markDirty();
          commitActiveField();
          renderAll();
          showRawSummary();
          maybeAutoLookupImportedIds();
        }
      });
      if (result === null) showRawModal(text);
    });
    copyRawFull.addEventListener('click', async () => {
      commitActiveField();
      try {
        assertJsonTextWithinLimit(rawFull.value, { label: 'Full Raw JSON input' });
      } catch (err) {
        const message = errorMessage('Could not copy full JSON', err);
        setInlineError('rawError', message);
        setStatus(message, 'err');
        return;
      }
      const ok = await copyTextToClipboard(rawFull.value);
      rawCopyStatus.textContent = ok ? 'Copied to clipboard.' : 'Copy failed. Select the text manually.';
      setStatus(ok ? 'Copied full JSON' : 'Copy failed. Select the text manually.', ok ? 'ok' : 'warn');
    });
  } catch (err) {
    reportModalBindingError('Raw JSON unavailable', err);
  }
}

let started = false;

function bindAppEvents() {
  const searchInput = bindInput('search', () => { updateSearchClearButton(); renderList(); });
  const clearSearchButton = el('clearSearch');
  function updateSearchClearButton() {
    if (!searchInput || !clearSearchButton) return;
    clearSearchButton.disabled = searchInput.value.length === 0;
  }
  function clearSearch() {
    if (!searchInput) return;
    searchInput.value = '';
    updateSearchClearButton();
    renderList();
    searchInput.focus();
  }
  updateSearchClearButton();
  if (searchInput) searchInput.addEventListener('keydown', e => { if (e.key === 'Escape' && e.currentTarget.value) { e.preventDefault(); clearSearch(); } });
  if (clearSearchButton) clearSearchButton.addEventListener('click', clearSearch);
  bindClick('addCategory', () => { commitActiveField(); getCategories().push(defaultCategory()); selectedIndex = getCategories().length - 1; markDirty(); renderAll(); });
  bindClick('sortByOrder', () => {
    commitActiveField();
    const result = sortCategoriesPreservingSelection(getCategories(), selectedIndex, compareCategoriesForImport);
    selectedIndex = result.selectedIndex;
    if (result.changed) markDirty();
    else setStatus('Categories are already sorted. No changes were made.', 'ok');
    renderAll();
  });
  bindClick('renumber', () => {
    commitActiveField();
    if (renumberCategories()) markDirty();
    else setStatus('Order and Priority are already renumbered. No changes were made.', 'ok');
    renderAll();
  });
  bindClick('lookupReferencedIds', () => { commitActiveField(); lookupReferencedIds().catch(err => setStatus(errorMessage('ID lookup failed', err), 'err')); });
  bindClick('showLookupCache', () => { commitActiveField(); showLookupCacheModal({ lookupCacheStats, clearLookupCache, isLookupCacheProducerActive: lookupCacheOperations.isActive, onLookupCacheProducerChange: lookupCacheOperations.subscribe, translate }); });
  bindClick('showHelp', () => { commitActiveField(); showHelpModal({ translate }); });
  bindClick('showPreferences', () => showPreferencesModal({
    getEditorPreferences: () => editorPreferences,
    applyEditorPreferences,
    setStatus,
    openModal,
    commitActiveField,
    translate
  }));
  bindClick('uploadFile', () => {
    commitActiveField();
    try {
      const input = requireEl('fileInput');
      input.value = '';
      input.click();
    } catch (err) {
      setStatus(errorMessage('Upload unavailable', err), 'err');
    }
  });

  bindClick('showExportCopy', async () => {
    commitActiveField();
    if (getCategories().length === 0) { updateExportControls(); setStatus('Add or import at least one category before exporting.', 'warn'); return; }
    let busyShown = false;
    try {
      const snapshot = await makeCompatibleRevisionedExportSnapshot('Generating export', 'Compressing JSON to gzip+Base64...', () => { busyShown = true; });
      if (!snapshot) return;
      const b64 = snapshot.value;
      hideBusy(); busyShown = false;
      if (isModalOpen()) {
        setStatus('Export generation finished while another dialog was active. Close it and run Export / Copy again.', 'warn');
        return;
      }
      const snapshotCurrent = isSnapshotCurrent(snapshot.revision, dataRevision);
      const wrap = document.createElement('div');
      const snapshotExplanation = snapshotCurrent
        ? 'Current gzip+Base64 export. Automatic clipboard copy will be attempted if the browser allows it.'
        : 'This gzip+Base64 export represents earlier editor data and is not the current config. Automatic clipboard copy will still be attempted.';
      wrap.innerHTML = `<p class="hint">${snapshotExplanation}</p><div id="exportError" class="modal-error hidden" role="alert"></div><textarea id="exportText" class="raw" readonly>${escapeHtml(b64)}</textarea><div class="row modal-action-row"><button id="copyExportAgain" class="primary">Copy again</button></div><p class="hint" id="exportCopyStatus"></p>`;
      openModal('Export / Copy', wrap);
      saveSnapshotIfCurrent(snapshot.revision, dataRevision, {
        onSaved: () => markSaved('Exported'),
        onStale: () => setStatus(
          dirty
            ? 'Generated export snapshot succeeded, but newer changes remain unexported.'
            : 'Generated export snapshot represents earlier editor data and is not the current config.',
          'warn'
        )
      });
      const copied = await copyTextToClipboard(b64);
      const exportCopyStatus = requireScopedEl(wrap, '#exportCopyStatus', 'export');
      const exportText = requireScopedEl(wrap, '#exportText', 'export');
      const copyExportAgain = requireScopedEl(wrap, '#copyExportAgain', 'export');
      exportCopyStatus.textContent = copied ? 'Copied to clipboard.' : 'Automatic copy was blocked by the browser. Use “Copy again” or select the text manually.';
      copyExportAgain.addEventListener('click', async () => {
        commitActiveField();
        const ok = await copyTextToClipboard(exportText.value);
        exportCopyStatus.textContent = ok ? 'Copied to clipboard.' : 'Copy failed. Select the text manually.';
        setInlineError('exportError', ok ? '' : 'Copy failed. Select the export text manually.');
      });
    } catch (err) { if (busyShown) hideBusy(); setStatus(errorMessage('Export failed', err), 'err'); }
  });

  bindClick('downloadBase64', async () => {
    commitActiveField();
    if (getCategories().length === 0) { updateExportControls(); setStatus('Add or import at least one category before downloading.', 'warn'); return; }
    let busyShown = false;
    try {
      const snapshot = await makeCompatibleRevisionedExportSnapshot('Generating download', 'Compressing JSON to gzip+Base64...', () => { busyShown = true; });
      if (!snapshot) return;
      downloadText(EXPORT_FILENAME, snapshot.value, 'text/plain', { onDownloaded(filename) {
        saveSnapshotIfCurrent(snapshot.revision, dataRevision, {
          onSaved() { markSaved('Downloaded'); setStatus(`Downloaded ${filename}`, 'ok'); },
          onStale() {
            setStatus(
              dirty
                ? `Downloaded ${filename}, but newer changes remain unexported.`
                : `Downloaded ${filename}, but it represents earlier editor data and is not the current config.`,
              'warn'
            );
          }
        });
      } });
    }
    catch (err) { setStatus(errorMessage('Download failed', err), 'err'); }
    finally { if (busyShown) hideBusy(); }
  });

  bindChange('fileInput', async e => {
    commitActiveField();
    const file = e.target.files[0];
    if (!file) return;
    try {
      await importText(await readImportFileText(file), file.name);
    } catch (err) { setStatus(errorMessage('Could not load file', err), 'err'); }
  });

  bindClick('showImport', () => showImportModal());
  bindClick('showRaw', () => showRawModal());

  bindClick('closeModal', closeModal);
  bindClick('modalBackdrop', e => { if (e.target === e.currentTarget) closeModal(); });
  document.addEventListener('keydown', e => {
    const backdrop = el('modalBackdrop');
    trapModalFocus(e);
    if (e.key === 'Escape' && backdrop && !backdrop.classList.contains('hidden')) closeModal();
  });
  window.addEventListener('beforeunload', e => { commitActiveField(); if (!dirty) return; e.preventDefault(); e.returnValue = ''; });
}

function getStylesheetLink() {
  const link = document.getElementById('appStylesheet');
  return link instanceof HTMLLinkElement ? link : null;
}

function isStylesheetReady(link) {
  if (!link) return true;
  try {
    return [...document.styleSheets].some(sheet => sheet.ownerNode === link);
  } catch {
    return false;
  }
}

function waitForStylesheetReady() {
  const link = getStylesheetLink();
  if (isStylesheetReady(link)) return Promise.resolve();
  return new Promise(resolve => {
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      link?.removeEventListener('load', finish);
      link?.removeEventListener('error', finish);
      resolve();
    };
    link.addEventListener('load', finish, { once: true });
    link.addEventListener('error', finish, { once: true });
    setTimeout(finish, 250);
  });
}

function startApp() {
  if (started) return;
  started = true;
  applyApplicationChromeLocalization(translate);
  bindAppEvents();
  applyEditorPreferences();
  waitForStylesheetReady().then(renderAll);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', startApp, { once: true });
} else {
  startApp();
}
