export const LOOKUP_CACHE_KEY = 'aetherbagsEditorLookupCache';
export const EDITOR_PREFERENCES_KEY = 'aetherbagsEditorPreferences';

export const DEFAULT_EDITOR_PREFERENCES = Object.freeze({
  theme: 'system',
  density: 'comfortable',
  autoGenerateDescriptions: false,
  autoLookupImportedIds: true
});

export const EDITOR_PREFERENCE_OPTIONS = Object.freeze({
  theme: Object.freeze(['system', 'dark', 'light', 'high-contrast', 'aetherial', 'dalamud']),
  density: Object.freeze(['comfortable', 'compact'])
});

function normalizeEditorPreferenceValue(key, value) {
  return EDITOR_PREFERENCE_OPTIONS[key]?.includes(value) ? value : DEFAULT_EDITOR_PREFERENCES[key];
}

function normalizeBooleanPreference(key, value) {
  return typeof value === 'boolean' ? value : DEFAULT_EDITOR_PREFERENCES[key];
}

export function normalizeEditorPreferences(value) {
  const source = value && typeof value === 'object' ? value : {};
  return {
    theme: normalizeEditorPreferenceValue('theme', source.theme),
    density: normalizeEditorPreferenceValue('density', source.density),
    autoGenerateDescriptions: normalizeBooleanPreference('autoGenerateDescriptions', source.autoGenerateDescriptions),
    autoLookupImportedIds: normalizeBooleanPreference('autoLookupImportedIds', source.autoLookupImportedIds)
  };
}

export function emptyLookupCache() {
  return { Item: {}, ItemUICategory: {} };
}

function isPlainObject(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function normalizeLookupCacheBucket(value) {
  const bucket = {};
  if (!isPlainObject(value)) return bucket;
  for (const [key, name] of Object.entries(value)) {
    if (typeof name === 'string') Object.defineProperty(bucket, key, { value: name, enumerable: true, configurable: true, writable: true });
  }
  return bucket;
}

export function normalizeLookupCache(value) {
  if (!isPlainObject(value)) return emptyLookupCache();
  return {
    Item: normalizeLookupCacheBucket(value.Item),
    ItemUICategory: normalizeLookupCacheBucket(value.ItemUICategory)
  };
}

export function loadLookupCache(storage = globalThis.localStorage) {
  try {
    const raw = storage?.getItem?.(LOOKUP_CACHE_KEY);
    return normalizeLookupCache(raw ? JSON.parse(raw) : null);
  } catch {
    return emptyLookupCache();
  }
}

export function persistLookupCache(lookupCache) {
  try {
    localStorage.setItem(LOOKUP_CACHE_KEY, JSON.stringify(lookupCache));
  } catch {
    // If storage is full or blocked, lookup caching is skipped.
  }
}

export function removeLookupCache() {
  try {
    localStorage.removeItem(LOOKUP_CACHE_KEY);
  } catch {
    // If storage is blocked, the in-memory cache can still be cleared.
  }
}

export function loadEditorPreferences(storage = globalThis.localStorage) {
  try {
    const raw = storage?.getItem?.(EDITOR_PREFERENCES_KEY);
    return normalizeEditorPreferences(raw ? JSON.parse(raw) : null);
  } catch {
    return normalizeEditorPreferences(null);
  }
}

export function persistEditorPreferences(preferences, storage = globalThis.localStorage) {
  const normalized = normalizeEditorPreferences(preferences);
  try {
    storage?.setItem?.(EDITOR_PREFERENCES_KEY, JSON.stringify(normalized));
  } catch {
    // Appearance preferences are optional editor-only settings.
  }
  return normalized;
}
